// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/ctrip/ferriswheel/proto/workbook.proto

package com.ctrip.ferriswheel.proto.v1;

public interface AxisBandOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ferriswheel.v1.AxisBand)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ferriswheel.v1.Interval interval = 1;</code>
   */
  boolean hasInterval();
  /**
   * <code>.ferriswheel.v1.Interval interval = 1;</code>
   */
  com.ctrip.ferriswheel.proto.v1.Interval getInterval();
  /**
   * <code>.ferriswheel.v1.Interval interval = 1;</code>
   */
  com.ctrip.ferriswheel.proto.v1.IntervalOrBuilder getIntervalOrBuilder();

  /**
   * <code>string label = 2;</code>
   */
  java.lang.String getLabel();
  /**
   * <code>string label = 2;</code>
   */
  com.google.protobuf.ByteString
      getLabelBytes();

  /**
   * <code>.ferriswheel.v1.Color color = 3;</code>
   */
  boolean hasColor();
  /**
   * <code>.ferriswheel.v1.Color color = 3;</code>
   */
  com.ctrip.ferriswheel.proto.v1.Color getColor();
  /**
   * <code>.ferriswheel.v1.Color color = 3;</code>
   */
  com.ctrip.ferriswheel.proto.v1.ColorOrBuilder getColorOrBuilder();
}
