// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/ctrip/ferriswheel/proto/workbook.proto

package com.ctrip.ferriswheel.proto.v1;

/**
 * Protobuf type {@code ferriswheel.v1.Chart}
 */
public  final class Chart extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ferriswheel.v1.Chart)
    ChartOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Chart.newBuilder() to construct.
  private Chart(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Chart() {
    name_ = "";
    type_ = "";
    series_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Chart(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            type_ = s;
            break;
          }
          case 26: {
            com.ctrip.ferriswheel.proto.v1.UnionValue.Builder subBuilder = null;
            if (title_ != null) {
              subBuilder = title_.toBuilder();
            }
            title_ = input.readMessage(com.ctrip.ferriswheel.proto.v1.UnionValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(title_);
              title_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            com.ctrip.ferriswheel.proto.v1.UnionValue.Builder subBuilder = null;
            if (categories_ != null) {
              subBuilder = categories_.toBuilder();
            }
            categories_ = input.readMessage(com.ctrip.ferriswheel.proto.v1.UnionValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(categories_);
              categories_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000010) != 0)) {
              series_ = new java.util.ArrayList<com.ctrip.ferriswheel.proto.v1.Series>();
              mutable_bitField0_ |= 0x00000010;
            }
            series_.add(
                input.readMessage(com.ctrip.ferriswheel.proto.v1.Series.parser(), extensionRegistry));
            break;
          }
          case 50: {
            com.ctrip.ferriswheel.proto.v1.Layout.Builder subBuilder = null;
            if (layout_ != null) {
              subBuilder = layout_.toBuilder();
            }
            layout_ = input.readMessage(com.ctrip.ferriswheel.proto.v1.Layout.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(layout_);
              layout_ = subBuilder.buildPartial();
            }

            break;
          }
          case 58: {
            com.ctrip.ferriswheel.proto.v1.ChartBinder.Builder subBuilder = null;
            if (binder_ != null) {
              subBuilder = binder_.toBuilder();
            }
            binder_ = input.readMessage(com.ctrip.ferriswheel.proto.v1.ChartBinder.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(binder_);
              binder_ = subBuilder.buildPartial();
            }

            break;
          }
          case 66: {
            com.ctrip.ferriswheel.proto.v1.Axis.Builder subBuilder = null;
            if (xAxis_ != null) {
              subBuilder = xAxis_.toBuilder();
            }
            xAxis_ = input.readMessage(com.ctrip.ferriswheel.proto.v1.Axis.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(xAxis_);
              xAxis_ = subBuilder.buildPartial();
            }

            break;
          }
          case 74: {
            com.ctrip.ferriswheel.proto.v1.Axis.Builder subBuilder = null;
            if (yAxis_ != null) {
              subBuilder = yAxis_.toBuilder();
            }
            yAxis_ = input.readMessage(com.ctrip.ferriswheel.proto.v1.Axis.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(yAxis_);
              yAxis_ = subBuilder.buildPartial();
            }

            break;
          }
          case 82: {
            com.ctrip.ferriswheel.proto.v1.Axis.Builder subBuilder = null;
            if (zAxis_ != null) {
              subBuilder = zAxis_.toBuilder();
            }
            zAxis_ = input.readMessage(com.ctrip.ferriswheel.proto.v1.Axis.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(zAxis_);
              zAxis_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000010) != 0)) {
        series_ = java.util.Collections.unmodifiableList(series_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ctrip.ferriswheel.proto.v1.WorkbookOuterClass.internal_static_ferriswheel_v1_Chart_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ctrip.ferriswheel.proto.v1.WorkbookOuterClass.internal_static_ferriswheel_v1_Chart_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ctrip.ferriswheel.proto.v1.Chart.class, com.ctrip.ferriswheel.proto.v1.Chart.Builder.class);
  }

  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 1;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_FIELD_NUMBER = 2;
  private volatile java.lang.Object type_;
  /**
   * <code>string type = 2;</code>
   */
  public java.lang.String getType() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      type_ = s;
      return s;
    }
  }
  /**
   * <code>string type = 2;</code>
   */
  public com.google.protobuf.ByteString
      getTypeBytes() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      type_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TITLE_FIELD_NUMBER = 3;
  private com.ctrip.ferriswheel.proto.v1.UnionValue title_;
  /**
   * <code>.ferriswheel.v1.UnionValue title = 3;</code>
   */
  public boolean hasTitle() {
    return title_ != null;
  }
  /**
   * <code>.ferriswheel.v1.UnionValue title = 3;</code>
   */
  public com.ctrip.ferriswheel.proto.v1.UnionValue getTitle() {
    return title_ == null ? com.ctrip.ferriswheel.proto.v1.UnionValue.getDefaultInstance() : title_;
  }
  /**
   * <code>.ferriswheel.v1.UnionValue title = 3;</code>
   */
  public com.ctrip.ferriswheel.proto.v1.UnionValueOrBuilder getTitleOrBuilder() {
    return getTitle();
  }

  public static final int CATEGORIES_FIELD_NUMBER = 4;
  private com.ctrip.ferriswheel.proto.v1.UnionValue categories_;
  /**
   * <code>.ferriswheel.v1.UnionValue categories = 4;</code>
   */
  public boolean hasCategories() {
    return categories_ != null;
  }
  /**
   * <code>.ferriswheel.v1.UnionValue categories = 4;</code>
   */
  public com.ctrip.ferriswheel.proto.v1.UnionValue getCategories() {
    return categories_ == null ? com.ctrip.ferriswheel.proto.v1.UnionValue.getDefaultInstance() : categories_;
  }
  /**
   * <code>.ferriswheel.v1.UnionValue categories = 4;</code>
   */
  public com.ctrip.ferriswheel.proto.v1.UnionValueOrBuilder getCategoriesOrBuilder() {
    return getCategories();
  }

  public static final int SERIES_FIELD_NUMBER = 5;
  private java.util.List<com.ctrip.ferriswheel.proto.v1.Series> series_;
  /**
   * <code>repeated .ferriswheel.v1.Series series = 5;</code>
   */
  public java.util.List<com.ctrip.ferriswheel.proto.v1.Series> getSeriesList() {
    return series_;
  }
  /**
   * <code>repeated .ferriswheel.v1.Series series = 5;</code>
   */
  public java.util.List<? extends com.ctrip.ferriswheel.proto.v1.SeriesOrBuilder> 
      getSeriesOrBuilderList() {
    return series_;
  }
  /**
   * <code>repeated .ferriswheel.v1.Series series = 5;</code>
   */
  public int getSeriesCount() {
    return series_.size();
  }
  /**
   * <code>repeated .ferriswheel.v1.Series series = 5;</code>
   */
  public com.ctrip.ferriswheel.proto.v1.Series getSeries(int index) {
    return series_.get(index);
  }
  /**
   * <code>repeated .ferriswheel.v1.Series series = 5;</code>
   */
  public com.ctrip.ferriswheel.proto.v1.SeriesOrBuilder getSeriesOrBuilder(
      int index) {
    return series_.get(index);
  }

  public static final int LAYOUT_FIELD_NUMBER = 6;
  private com.ctrip.ferriswheel.proto.v1.Layout layout_;
  /**
   * <code>.ferriswheel.v1.Layout layout = 6;</code>
   */
  public boolean hasLayout() {
    return layout_ != null;
  }
  /**
   * <code>.ferriswheel.v1.Layout layout = 6;</code>
   */
  public com.ctrip.ferriswheel.proto.v1.Layout getLayout() {
    return layout_ == null ? com.ctrip.ferriswheel.proto.v1.Layout.getDefaultInstance() : layout_;
  }
  /**
   * <code>.ferriswheel.v1.Layout layout = 6;</code>
   */
  public com.ctrip.ferriswheel.proto.v1.LayoutOrBuilder getLayoutOrBuilder() {
    return getLayout();
  }

  public static final int BINDER_FIELD_NUMBER = 7;
  private com.ctrip.ferriswheel.proto.v1.ChartBinder binder_;
  /**
   * <code>.ferriswheel.v1.ChartBinder binder = 7;</code>
   */
  public boolean hasBinder() {
    return binder_ != null;
  }
  /**
   * <code>.ferriswheel.v1.ChartBinder binder = 7;</code>
   */
  public com.ctrip.ferriswheel.proto.v1.ChartBinder getBinder() {
    return binder_ == null ? com.ctrip.ferriswheel.proto.v1.ChartBinder.getDefaultInstance() : binder_;
  }
  /**
   * <code>.ferriswheel.v1.ChartBinder binder = 7;</code>
   */
  public com.ctrip.ferriswheel.proto.v1.ChartBinderOrBuilder getBinderOrBuilder() {
    return getBinder();
  }

  public static final int X_AXIS_FIELD_NUMBER = 8;
  private com.ctrip.ferriswheel.proto.v1.Axis xAxis_;
  /**
   * <code>.ferriswheel.v1.Axis x_axis = 8;</code>
   */
  public boolean hasXAxis() {
    return xAxis_ != null;
  }
  /**
   * <code>.ferriswheel.v1.Axis x_axis = 8;</code>
   */
  public com.ctrip.ferriswheel.proto.v1.Axis getXAxis() {
    return xAxis_ == null ? com.ctrip.ferriswheel.proto.v1.Axis.getDefaultInstance() : xAxis_;
  }
  /**
   * <code>.ferriswheel.v1.Axis x_axis = 8;</code>
   */
  public com.ctrip.ferriswheel.proto.v1.AxisOrBuilder getXAxisOrBuilder() {
    return getXAxis();
  }

  public static final int Y_AXIS_FIELD_NUMBER = 9;
  private com.ctrip.ferriswheel.proto.v1.Axis yAxis_;
  /**
   * <code>.ferriswheel.v1.Axis y_axis = 9;</code>
   */
  public boolean hasYAxis() {
    return yAxis_ != null;
  }
  /**
   * <code>.ferriswheel.v1.Axis y_axis = 9;</code>
   */
  public com.ctrip.ferriswheel.proto.v1.Axis getYAxis() {
    return yAxis_ == null ? com.ctrip.ferriswheel.proto.v1.Axis.getDefaultInstance() : yAxis_;
  }
  /**
   * <code>.ferriswheel.v1.Axis y_axis = 9;</code>
   */
  public com.ctrip.ferriswheel.proto.v1.AxisOrBuilder getYAxisOrBuilder() {
    return getYAxis();
  }

  public static final int Z_AXIS_FIELD_NUMBER = 10;
  private com.ctrip.ferriswheel.proto.v1.Axis zAxis_;
  /**
   * <code>.ferriswheel.v1.Axis z_axis = 10;</code>
   */
  public boolean hasZAxis() {
    return zAxis_ != null;
  }
  /**
   * <code>.ferriswheel.v1.Axis z_axis = 10;</code>
   */
  public com.ctrip.ferriswheel.proto.v1.Axis getZAxis() {
    return zAxis_ == null ? com.ctrip.ferriswheel.proto.v1.Axis.getDefaultInstance() : zAxis_;
  }
  /**
   * <code>.ferriswheel.v1.Axis z_axis = 10;</code>
   */
  public com.ctrip.ferriswheel.proto.v1.AxisOrBuilder getZAxisOrBuilder() {
    return getZAxis();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (!getTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, type_);
    }
    if (title_ != null) {
      output.writeMessage(3, getTitle());
    }
    if (categories_ != null) {
      output.writeMessage(4, getCategories());
    }
    for (int i = 0; i < series_.size(); i++) {
      output.writeMessage(5, series_.get(i));
    }
    if (layout_ != null) {
      output.writeMessage(6, getLayout());
    }
    if (binder_ != null) {
      output.writeMessage(7, getBinder());
    }
    if (xAxis_ != null) {
      output.writeMessage(8, getXAxis());
    }
    if (yAxis_ != null) {
      output.writeMessage(9, getYAxis());
    }
    if (zAxis_ != null) {
      output.writeMessage(10, getZAxis());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (!getTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, type_);
    }
    if (title_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getTitle());
    }
    if (categories_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getCategories());
    }
    for (int i = 0; i < series_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, series_.get(i));
    }
    if (layout_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getLayout());
    }
    if (binder_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getBinder());
    }
    if (xAxis_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getXAxis());
    }
    if (yAxis_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getYAxis());
    }
    if (zAxis_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, getZAxis());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ctrip.ferriswheel.proto.v1.Chart)) {
      return super.equals(obj);
    }
    com.ctrip.ferriswheel.proto.v1.Chart other = (com.ctrip.ferriswheel.proto.v1.Chart) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (!getType()
        .equals(other.getType())) return false;
    if (hasTitle() != other.hasTitle()) return false;
    if (hasTitle()) {
      if (!getTitle()
          .equals(other.getTitle())) return false;
    }
    if (hasCategories() != other.hasCategories()) return false;
    if (hasCategories()) {
      if (!getCategories()
          .equals(other.getCategories())) return false;
    }
    if (!getSeriesList()
        .equals(other.getSeriesList())) return false;
    if (hasLayout() != other.hasLayout()) return false;
    if (hasLayout()) {
      if (!getLayout()
          .equals(other.getLayout())) return false;
    }
    if (hasBinder() != other.hasBinder()) return false;
    if (hasBinder()) {
      if (!getBinder()
          .equals(other.getBinder())) return false;
    }
    if (hasXAxis() != other.hasXAxis()) return false;
    if (hasXAxis()) {
      if (!getXAxis()
          .equals(other.getXAxis())) return false;
    }
    if (hasYAxis() != other.hasYAxis()) return false;
    if (hasYAxis()) {
      if (!getYAxis()
          .equals(other.getYAxis())) return false;
    }
    if (hasZAxis() != other.hasZAxis()) return false;
    if (hasZAxis()) {
      if (!getZAxis()
          .equals(other.getZAxis())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType().hashCode();
    if (hasTitle()) {
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
    }
    if (hasCategories()) {
      hash = (37 * hash) + CATEGORIES_FIELD_NUMBER;
      hash = (53 * hash) + getCategories().hashCode();
    }
    if (getSeriesCount() > 0) {
      hash = (37 * hash) + SERIES_FIELD_NUMBER;
      hash = (53 * hash) + getSeriesList().hashCode();
    }
    if (hasLayout()) {
      hash = (37 * hash) + LAYOUT_FIELD_NUMBER;
      hash = (53 * hash) + getLayout().hashCode();
    }
    if (hasBinder()) {
      hash = (37 * hash) + BINDER_FIELD_NUMBER;
      hash = (53 * hash) + getBinder().hashCode();
    }
    if (hasXAxis()) {
      hash = (37 * hash) + X_AXIS_FIELD_NUMBER;
      hash = (53 * hash) + getXAxis().hashCode();
    }
    if (hasYAxis()) {
      hash = (37 * hash) + Y_AXIS_FIELD_NUMBER;
      hash = (53 * hash) + getYAxis().hashCode();
    }
    if (hasZAxis()) {
      hash = (37 * hash) + Z_AXIS_FIELD_NUMBER;
      hash = (53 * hash) + getZAxis().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ctrip.ferriswheel.proto.v1.Chart parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ctrip.ferriswheel.proto.v1.Chart parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ctrip.ferriswheel.proto.v1.Chart parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ctrip.ferriswheel.proto.v1.Chart parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ctrip.ferriswheel.proto.v1.Chart parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ctrip.ferriswheel.proto.v1.Chart parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ctrip.ferriswheel.proto.v1.Chart parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ctrip.ferriswheel.proto.v1.Chart parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ctrip.ferriswheel.proto.v1.Chart parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ctrip.ferriswheel.proto.v1.Chart parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ctrip.ferriswheel.proto.v1.Chart parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ctrip.ferriswheel.proto.v1.Chart parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ctrip.ferriswheel.proto.v1.Chart prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ferriswheel.v1.Chart}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ferriswheel.v1.Chart)
      com.ctrip.ferriswheel.proto.v1.ChartOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ctrip.ferriswheel.proto.v1.WorkbookOuterClass.internal_static_ferriswheel_v1_Chart_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ctrip.ferriswheel.proto.v1.WorkbookOuterClass.internal_static_ferriswheel_v1_Chart_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ctrip.ferriswheel.proto.v1.Chart.class, com.ctrip.ferriswheel.proto.v1.Chart.Builder.class);
    }

    // Construct using com.ctrip.ferriswheel.proto.v1.Chart.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getSeriesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      name_ = "";

      type_ = "";

      if (titleBuilder_ == null) {
        title_ = null;
      } else {
        title_ = null;
        titleBuilder_ = null;
      }
      if (categoriesBuilder_ == null) {
        categories_ = null;
      } else {
        categories_ = null;
        categoriesBuilder_ = null;
      }
      if (seriesBuilder_ == null) {
        series_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
      } else {
        seriesBuilder_.clear();
      }
      if (layoutBuilder_ == null) {
        layout_ = null;
      } else {
        layout_ = null;
        layoutBuilder_ = null;
      }
      if (binderBuilder_ == null) {
        binder_ = null;
      } else {
        binder_ = null;
        binderBuilder_ = null;
      }
      if (xAxisBuilder_ == null) {
        xAxis_ = null;
      } else {
        xAxis_ = null;
        xAxisBuilder_ = null;
      }
      if (yAxisBuilder_ == null) {
        yAxis_ = null;
      } else {
        yAxis_ = null;
        yAxisBuilder_ = null;
      }
      if (zAxisBuilder_ == null) {
        zAxis_ = null;
      } else {
        zAxis_ = null;
        zAxisBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ctrip.ferriswheel.proto.v1.WorkbookOuterClass.internal_static_ferriswheel_v1_Chart_descriptor;
    }

    @java.lang.Override
    public com.ctrip.ferriswheel.proto.v1.Chart getDefaultInstanceForType() {
      return com.ctrip.ferriswheel.proto.v1.Chart.getDefaultInstance();
    }

    @java.lang.Override
    public com.ctrip.ferriswheel.proto.v1.Chart build() {
      com.ctrip.ferriswheel.proto.v1.Chart result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ctrip.ferriswheel.proto.v1.Chart buildPartial() {
      com.ctrip.ferriswheel.proto.v1.Chart result = new com.ctrip.ferriswheel.proto.v1.Chart(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.name_ = name_;
      result.type_ = type_;
      if (titleBuilder_ == null) {
        result.title_ = title_;
      } else {
        result.title_ = titleBuilder_.build();
      }
      if (categoriesBuilder_ == null) {
        result.categories_ = categories_;
      } else {
        result.categories_ = categoriesBuilder_.build();
      }
      if (seriesBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0)) {
          series_ = java.util.Collections.unmodifiableList(series_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.series_ = series_;
      } else {
        result.series_ = seriesBuilder_.build();
      }
      if (layoutBuilder_ == null) {
        result.layout_ = layout_;
      } else {
        result.layout_ = layoutBuilder_.build();
      }
      if (binderBuilder_ == null) {
        result.binder_ = binder_;
      } else {
        result.binder_ = binderBuilder_.build();
      }
      if (xAxisBuilder_ == null) {
        result.xAxis_ = xAxis_;
      } else {
        result.xAxis_ = xAxisBuilder_.build();
      }
      if (yAxisBuilder_ == null) {
        result.yAxis_ = yAxis_;
      } else {
        result.yAxis_ = yAxisBuilder_.build();
      }
      if (zAxisBuilder_ == null) {
        result.zAxis_ = zAxis_;
      } else {
        result.zAxis_ = zAxisBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ctrip.ferriswheel.proto.v1.Chart) {
        return mergeFrom((com.ctrip.ferriswheel.proto.v1.Chart)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ctrip.ferriswheel.proto.v1.Chart other) {
      if (other == com.ctrip.ferriswheel.proto.v1.Chart.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getType().isEmpty()) {
        type_ = other.type_;
        onChanged();
      }
      if (other.hasTitle()) {
        mergeTitle(other.getTitle());
      }
      if (other.hasCategories()) {
        mergeCategories(other.getCategories());
      }
      if (seriesBuilder_ == null) {
        if (!other.series_.isEmpty()) {
          if (series_.isEmpty()) {
            series_ = other.series_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureSeriesIsMutable();
            series_.addAll(other.series_);
          }
          onChanged();
        }
      } else {
        if (!other.series_.isEmpty()) {
          if (seriesBuilder_.isEmpty()) {
            seriesBuilder_.dispose();
            seriesBuilder_ = null;
            series_ = other.series_;
            bitField0_ = (bitField0_ & ~0x00000010);
            seriesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSeriesFieldBuilder() : null;
          } else {
            seriesBuilder_.addAllMessages(other.series_);
          }
        }
      }
      if (other.hasLayout()) {
        mergeLayout(other.getLayout());
      }
      if (other.hasBinder()) {
        mergeBinder(other.getBinder());
      }
      if (other.hasXAxis()) {
        mergeXAxis(other.getXAxis());
      }
      if (other.hasYAxis()) {
        mergeYAxis(other.getYAxis());
      }
      if (other.hasZAxis()) {
        mergeZAxis(other.getZAxis());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ctrip.ferriswheel.proto.v1.Chart parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ctrip.ferriswheel.proto.v1.Chart) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object type_ = "";
    /**
     * <code>string type = 2;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string type = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string type = 2;</code>
     */
    public Builder setType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string type = 2;</code>
     */
    public Builder clearType() {
      
      type_ = getDefaultInstance().getType();
      onChanged();
      return this;
    }
    /**
     * <code>string type = 2;</code>
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      type_ = value;
      onChanged();
      return this;
    }

    private com.ctrip.ferriswheel.proto.v1.UnionValue title_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ctrip.ferriswheel.proto.v1.UnionValue, com.ctrip.ferriswheel.proto.v1.UnionValue.Builder, com.ctrip.ferriswheel.proto.v1.UnionValueOrBuilder> titleBuilder_;
    /**
     * <code>.ferriswheel.v1.UnionValue title = 3;</code>
     */
    public boolean hasTitle() {
      return titleBuilder_ != null || title_ != null;
    }
    /**
     * <code>.ferriswheel.v1.UnionValue title = 3;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.UnionValue getTitle() {
      if (titleBuilder_ == null) {
        return title_ == null ? com.ctrip.ferriswheel.proto.v1.UnionValue.getDefaultInstance() : title_;
      } else {
        return titleBuilder_.getMessage();
      }
    }
    /**
     * <code>.ferriswheel.v1.UnionValue title = 3;</code>
     */
    public Builder setTitle(com.ctrip.ferriswheel.proto.v1.UnionValue value) {
      if (titleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        title_ = value;
        onChanged();
      } else {
        titleBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.ferriswheel.v1.UnionValue title = 3;</code>
     */
    public Builder setTitle(
        com.ctrip.ferriswheel.proto.v1.UnionValue.Builder builderForValue) {
      if (titleBuilder_ == null) {
        title_ = builderForValue.build();
        onChanged();
      } else {
        titleBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.ferriswheel.v1.UnionValue title = 3;</code>
     */
    public Builder mergeTitle(com.ctrip.ferriswheel.proto.v1.UnionValue value) {
      if (titleBuilder_ == null) {
        if (title_ != null) {
          title_ =
            com.ctrip.ferriswheel.proto.v1.UnionValue.newBuilder(title_).mergeFrom(value).buildPartial();
        } else {
          title_ = value;
        }
        onChanged();
      } else {
        titleBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.ferriswheel.v1.UnionValue title = 3;</code>
     */
    public Builder clearTitle() {
      if (titleBuilder_ == null) {
        title_ = null;
        onChanged();
      } else {
        title_ = null;
        titleBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.ferriswheel.v1.UnionValue title = 3;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.UnionValue.Builder getTitleBuilder() {
      
      onChanged();
      return getTitleFieldBuilder().getBuilder();
    }
    /**
     * <code>.ferriswheel.v1.UnionValue title = 3;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.UnionValueOrBuilder getTitleOrBuilder() {
      if (titleBuilder_ != null) {
        return titleBuilder_.getMessageOrBuilder();
      } else {
        return title_ == null ?
            com.ctrip.ferriswheel.proto.v1.UnionValue.getDefaultInstance() : title_;
      }
    }
    /**
     * <code>.ferriswheel.v1.UnionValue title = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ctrip.ferriswheel.proto.v1.UnionValue, com.ctrip.ferriswheel.proto.v1.UnionValue.Builder, com.ctrip.ferriswheel.proto.v1.UnionValueOrBuilder> 
        getTitleFieldBuilder() {
      if (titleBuilder_ == null) {
        titleBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ctrip.ferriswheel.proto.v1.UnionValue, com.ctrip.ferriswheel.proto.v1.UnionValue.Builder, com.ctrip.ferriswheel.proto.v1.UnionValueOrBuilder>(
                getTitle(),
                getParentForChildren(),
                isClean());
        title_ = null;
      }
      return titleBuilder_;
    }

    private com.ctrip.ferriswheel.proto.v1.UnionValue categories_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ctrip.ferriswheel.proto.v1.UnionValue, com.ctrip.ferriswheel.proto.v1.UnionValue.Builder, com.ctrip.ferriswheel.proto.v1.UnionValueOrBuilder> categoriesBuilder_;
    /**
     * <code>.ferriswheel.v1.UnionValue categories = 4;</code>
     */
    public boolean hasCategories() {
      return categoriesBuilder_ != null || categories_ != null;
    }
    /**
     * <code>.ferriswheel.v1.UnionValue categories = 4;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.UnionValue getCategories() {
      if (categoriesBuilder_ == null) {
        return categories_ == null ? com.ctrip.ferriswheel.proto.v1.UnionValue.getDefaultInstance() : categories_;
      } else {
        return categoriesBuilder_.getMessage();
      }
    }
    /**
     * <code>.ferriswheel.v1.UnionValue categories = 4;</code>
     */
    public Builder setCategories(com.ctrip.ferriswheel.proto.v1.UnionValue value) {
      if (categoriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        categories_ = value;
        onChanged();
      } else {
        categoriesBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.ferriswheel.v1.UnionValue categories = 4;</code>
     */
    public Builder setCategories(
        com.ctrip.ferriswheel.proto.v1.UnionValue.Builder builderForValue) {
      if (categoriesBuilder_ == null) {
        categories_ = builderForValue.build();
        onChanged();
      } else {
        categoriesBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.ferriswheel.v1.UnionValue categories = 4;</code>
     */
    public Builder mergeCategories(com.ctrip.ferriswheel.proto.v1.UnionValue value) {
      if (categoriesBuilder_ == null) {
        if (categories_ != null) {
          categories_ =
            com.ctrip.ferriswheel.proto.v1.UnionValue.newBuilder(categories_).mergeFrom(value).buildPartial();
        } else {
          categories_ = value;
        }
        onChanged();
      } else {
        categoriesBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.ferriswheel.v1.UnionValue categories = 4;</code>
     */
    public Builder clearCategories() {
      if (categoriesBuilder_ == null) {
        categories_ = null;
        onChanged();
      } else {
        categories_ = null;
        categoriesBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.ferriswheel.v1.UnionValue categories = 4;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.UnionValue.Builder getCategoriesBuilder() {
      
      onChanged();
      return getCategoriesFieldBuilder().getBuilder();
    }
    /**
     * <code>.ferriswheel.v1.UnionValue categories = 4;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.UnionValueOrBuilder getCategoriesOrBuilder() {
      if (categoriesBuilder_ != null) {
        return categoriesBuilder_.getMessageOrBuilder();
      } else {
        return categories_ == null ?
            com.ctrip.ferriswheel.proto.v1.UnionValue.getDefaultInstance() : categories_;
      }
    }
    /**
     * <code>.ferriswheel.v1.UnionValue categories = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ctrip.ferriswheel.proto.v1.UnionValue, com.ctrip.ferriswheel.proto.v1.UnionValue.Builder, com.ctrip.ferriswheel.proto.v1.UnionValueOrBuilder> 
        getCategoriesFieldBuilder() {
      if (categoriesBuilder_ == null) {
        categoriesBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ctrip.ferriswheel.proto.v1.UnionValue, com.ctrip.ferriswheel.proto.v1.UnionValue.Builder, com.ctrip.ferriswheel.proto.v1.UnionValueOrBuilder>(
                getCategories(),
                getParentForChildren(),
                isClean());
        categories_ = null;
      }
      return categoriesBuilder_;
    }

    private java.util.List<com.ctrip.ferriswheel.proto.v1.Series> series_ =
      java.util.Collections.emptyList();
    private void ensureSeriesIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        series_ = new java.util.ArrayList<com.ctrip.ferriswheel.proto.v1.Series>(series_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ctrip.ferriswheel.proto.v1.Series, com.ctrip.ferriswheel.proto.v1.Series.Builder, com.ctrip.ferriswheel.proto.v1.SeriesOrBuilder> seriesBuilder_;

    /**
     * <code>repeated .ferriswheel.v1.Series series = 5;</code>
     */
    public java.util.List<com.ctrip.ferriswheel.proto.v1.Series> getSeriesList() {
      if (seriesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(series_);
      } else {
        return seriesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .ferriswheel.v1.Series series = 5;</code>
     */
    public int getSeriesCount() {
      if (seriesBuilder_ == null) {
        return series_.size();
      } else {
        return seriesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .ferriswheel.v1.Series series = 5;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.Series getSeries(int index) {
      if (seriesBuilder_ == null) {
        return series_.get(index);
      } else {
        return seriesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .ferriswheel.v1.Series series = 5;</code>
     */
    public Builder setSeries(
        int index, com.ctrip.ferriswheel.proto.v1.Series value) {
      if (seriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSeriesIsMutable();
        series_.set(index, value);
        onChanged();
      } else {
        seriesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ferriswheel.v1.Series series = 5;</code>
     */
    public Builder setSeries(
        int index, com.ctrip.ferriswheel.proto.v1.Series.Builder builderForValue) {
      if (seriesBuilder_ == null) {
        ensureSeriesIsMutable();
        series_.set(index, builderForValue.build());
        onChanged();
      } else {
        seriesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ferriswheel.v1.Series series = 5;</code>
     */
    public Builder addSeries(com.ctrip.ferriswheel.proto.v1.Series value) {
      if (seriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSeriesIsMutable();
        series_.add(value);
        onChanged();
      } else {
        seriesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .ferriswheel.v1.Series series = 5;</code>
     */
    public Builder addSeries(
        int index, com.ctrip.ferriswheel.proto.v1.Series value) {
      if (seriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSeriesIsMutable();
        series_.add(index, value);
        onChanged();
      } else {
        seriesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ferriswheel.v1.Series series = 5;</code>
     */
    public Builder addSeries(
        com.ctrip.ferriswheel.proto.v1.Series.Builder builderForValue) {
      if (seriesBuilder_ == null) {
        ensureSeriesIsMutable();
        series_.add(builderForValue.build());
        onChanged();
      } else {
        seriesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ferriswheel.v1.Series series = 5;</code>
     */
    public Builder addSeries(
        int index, com.ctrip.ferriswheel.proto.v1.Series.Builder builderForValue) {
      if (seriesBuilder_ == null) {
        ensureSeriesIsMutable();
        series_.add(index, builderForValue.build());
        onChanged();
      } else {
        seriesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ferriswheel.v1.Series series = 5;</code>
     */
    public Builder addAllSeries(
        java.lang.Iterable<? extends com.ctrip.ferriswheel.proto.v1.Series> values) {
      if (seriesBuilder_ == null) {
        ensureSeriesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, series_);
        onChanged();
      } else {
        seriesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .ferriswheel.v1.Series series = 5;</code>
     */
    public Builder clearSeries() {
      if (seriesBuilder_ == null) {
        series_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        seriesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .ferriswheel.v1.Series series = 5;</code>
     */
    public Builder removeSeries(int index) {
      if (seriesBuilder_ == null) {
        ensureSeriesIsMutable();
        series_.remove(index);
        onChanged();
      } else {
        seriesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .ferriswheel.v1.Series series = 5;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.Series.Builder getSeriesBuilder(
        int index) {
      return getSeriesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .ferriswheel.v1.Series series = 5;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.SeriesOrBuilder getSeriesOrBuilder(
        int index) {
      if (seriesBuilder_ == null) {
        return series_.get(index);  } else {
        return seriesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .ferriswheel.v1.Series series = 5;</code>
     */
    public java.util.List<? extends com.ctrip.ferriswheel.proto.v1.SeriesOrBuilder> 
         getSeriesOrBuilderList() {
      if (seriesBuilder_ != null) {
        return seriesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(series_);
      }
    }
    /**
     * <code>repeated .ferriswheel.v1.Series series = 5;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.Series.Builder addSeriesBuilder() {
      return getSeriesFieldBuilder().addBuilder(
          com.ctrip.ferriswheel.proto.v1.Series.getDefaultInstance());
    }
    /**
     * <code>repeated .ferriswheel.v1.Series series = 5;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.Series.Builder addSeriesBuilder(
        int index) {
      return getSeriesFieldBuilder().addBuilder(
          index, com.ctrip.ferriswheel.proto.v1.Series.getDefaultInstance());
    }
    /**
     * <code>repeated .ferriswheel.v1.Series series = 5;</code>
     */
    public java.util.List<com.ctrip.ferriswheel.proto.v1.Series.Builder> 
         getSeriesBuilderList() {
      return getSeriesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ctrip.ferriswheel.proto.v1.Series, com.ctrip.ferriswheel.proto.v1.Series.Builder, com.ctrip.ferriswheel.proto.v1.SeriesOrBuilder> 
        getSeriesFieldBuilder() {
      if (seriesBuilder_ == null) {
        seriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.ctrip.ferriswheel.proto.v1.Series, com.ctrip.ferriswheel.proto.v1.Series.Builder, com.ctrip.ferriswheel.proto.v1.SeriesOrBuilder>(
                series_,
                ((bitField0_ & 0x00000010) != 0),
                getParentForChildren(),
                isClean());
        series_ = null;
      }
      return seriesBuilder_;
    }

    private com.ctrip.ferriswheel.proto.v1.Layout layout_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ctrip.ferriswheel.proto.v1.Layout, com.ctrip.ferriswheel.proto.v1.Layout.Builder, com.ctrip.ferriswheel.proto.v1.LayoutOrBuilder> layoutBuilder_;
    /**
     * <code>.ferriswheel.v1.Layout layout = 6;</code>
     */
    public boolean hasLayout() {
      return layoutBuilder_ != null || layout_ != null;
    }
    /**
     * <code>.ferriswheel.v1.Layout layout = 6;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.Layout getLayout() {
      if (layoutBuilder_ == null) {
        return layout_ == null ? com.ctrip.ferriswheel.proto.v1.Layout.getDefaultInstance() : layout_;
      } else {
        return layoutBuilder_.getMessage();
      }
    }
    /**
     * <code>.ferriswheel.v1.Layout layout = 6;</code>
     */
    public Builder setLayout(com.ctrip.ferriswheel.proto.v1.Layout value) {
      if (layoutBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        layout_ = value;
        onChanged();
      } else {
        layoutBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.ferriswheel.v1.Layout layout = 6;</code>
     */
    public Builder setLayout(
        com.ctrip.ferriswheel.proto.v1.Layout.Builder builderForValue) {
      if (layoutBuilder_ == null) {
        layout_ = builderForValue.build();
        onChanged();
      } else {
        layoutBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.ferriswheel.v1.Layout layout = 6;</code>
     */
    public Builder mergeLayout(com.ctrip.ferriswheel.proto.v1.Layout value) {
      if (layoutBuilder_ == null) {
        if (layout_ != null) {
          layout_ =
            com.ctrip.ferriswheel.proto.v1.Layout.newBuilder(layout_).mergeFrom(value).buildPartial();
        } else {
          layout_ = value;
        }
        onChanged();
      } else {
        layoutBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.ferriswheel.v1.Layout layout = 6;</code>
     */
    public Builder clearLayout() {
      if (layoutBuilder_ == null) {
        layout_ = null;
        onChanged();
      } else {
        layout_ = null;
        layoutBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.ferriswheel.v1.Layout layout = 6;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.Layout.Builder getLayoutBuilder() {
      
      onChanged();
      return getLayoutFieldBuilder().getBuilder();
    }
    /**
     * <code>.ferriswheel.v1.Layout layout = 6;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.LayoutOrBuilder getLayoutOrBuilder() {
      if (layoutBuilder_ != null) {
        return layoutBuilder_.getMessageOrBuilder();
      } else {
        return layout_ == null ?
            com.ctrip.ferriswheel.proto.v1.Layout.getDefaultInstance() : layout_;
      }
    }
    /**
     * <code>.ferriswheel.v1.Layout layout = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ctrip.ferriswheel.proto.v1.Layout, com.ctrip.ferriswheel.proto.v1.Layout.Builder, com.ctrip.ferriswheel.proto.v1.LayoutOrBuilder> 
        getLayoutFieldBuilder() {
      if (layoutBuilder_ == null) {
        layoutBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ctrip.ferriswheel.proto.v1.Layout, com.ctrip.ferriswheel.proto.v1.Layout.Builder, com.ctrip.ferriswheel.proto.v1.LayoutOrBuilder>(
                getLayout(),
                getParentForChildren(),
                isClean());
        layout_ = null;
      }
      return layoutBuilder_;
    }

    private com.ctrip.ferriswheel.proto.v1.ChartBinder binder_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ctrip.ferriswheel.proto.v1.ChartBinder, com.ctrip.ferriswheel.proto.v1.ChartBinder.Builder, com.ctrip.ferriswheel.proto.v1.ChartBinderOrBuilder> binderBuilder_;
    /**
     * <code>.ferriswheel.v1.ChartBinder binder = 7;</code>
     */
    public boolean hasBinder() {
      return binderBuilder_ != null || binder_ != null;
    }
    /**
     * <code>.ferriswheel.v1.ChartBinder binder = 7;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.ChartBinder getBinder() {
      if (binderBuilder_ == null) {
        return binder_ == null ? com.ctrip.ferriswheel.proto.v1.ChartBinder.getDefaultInstance() : binder_;
      } else {
        return binderBuilder_.getMessage();
      }
    }
    /**
     * <code>.ferriswheel.v1.ChartBinder binder = 7;</code>
     */
    public Builder setBinder(com.ctrip.ferriswheel.proto.v1.ChartBinder value) {
      if (binderBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        binder_ = value;
        onChanged();
      } else {
        binderBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.ferriswheel.v1.ChartBinder binder = 7;</code>
     */
    public Builder setBinder(
        com.ctrip.ferriswheel.proto.v1.ChartBinder.Builder builderForValue) {
      if (binderBuilder_ == null) {
        binder_ = builderForValue.build();
        onChanged();
      } else {
        binderBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.ferriswheel.v1.ChartBinder binder = 7;</code>
     */
    public Builder mergeBinder(com.ctrip.ferriswheel.proto.v1.ChartBinder value) {
      if (binderBuilder_ == null) {
        if (binder_ != null) {
          binder_ =
            com.ctrip.ferriswheel.proto.v1.ChartBinder.newBuilder(binder_).mergeFrom(value).buildPartial();
        } else {
          binder_ = value;
        }
        onChanged();
      } else {
        binderBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.ferriswheel.v1.ChartBinder binder = 7;</code>
     */
    public Builder clearBinder() {
      if (binderBuilder_ == null) {
        binder_ = null;
        onChanged();
      } else {
        binder_ = null;
        binderBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.ferriswheel.v1.ChartBinder binder = 7;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.ChartBinder.Builder getBinderBuilder() {
      
      onChanged();
      return getBinderFieldBuilder().getBuilder();
    }
    /**
     * <code>.ferriswheel.v1.ChartBinder binder = 7;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.ChartBinderOrBuilder getBinderOrBuilder() {
      if (binderBuilder_ != null) {
        return binderBuilder_.getMessageOrBuilder();
      } else {
        return binder_ == null ?
            com.ctrip.ferriswheel.proto.v1.ChartBinder.getDefaultInstance() : binder_;
      }
    }
    /**
     * <code>.ferriswheel.v1.ChartBinder binder = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ctrip.ferriswheel.proto.v1.ChartBinder, com.ctrip.ferriswheel.proto.v1.ChartBinder.Builder, com.ctrip.ferriswheel.proto.v1.ChartBinderOrBuilder> 
        getBinderFieldBuilder() {
      if (binderBuilder_ == null) {
        binderBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ctrip.ferriswheel.proto.v1.ChartBinder, com.ctrip.ferriswheel.proto.v1.ChartBinder.Builder, com.ctrip.ferriswheel.proto.v1.ChartBinderOrBuilder>(
                getBinder(),
                getParentForChildren(),
                isClean());
        binder_ = null;
      }
      return binderBuilder_;
    }

    private com.ctrip.ferriswheel.proto.v1.Axis xAxis_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ctrip.ferriswheel.proto.v1.Axis, com.ctrip.ferriswheel.proto.v1.Axis.Builder, com.ctrip.ferriswheel.proto.v1.AxisOrBuilder> xAxisBuilder_;
    /**
     * <code>.ferriswheel.v1.Axis x_axis = 8;</code>
     */
    public boolean hasXAxis() {
      return xAxisBuilder_ != null || xAxis_ != null;
    }
    /**
     * <code>.ferriswheel.v1.Axis x_axis = 8;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.Axis getXAxis() {
      if (xAxisBuilder_ == null) {
        return xAxis_ == null ? com.ctrip.ferriswheel.proto.v1.Axis.getDefaultInstance() : xAxis_;
      } else {
        return xAxisBuilder_.getMessage();
      }
    }
    /**
     * <code>.ferriswheel.v1.Axis x_axis = 8;</code>
     */
    public Builder setXAxis(com.ctrip.ferriswheel.proto.v1.Axis value) {
      if (xAxisBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        xAxis_ = value;
        onChanged();
      } else {
        xAxisBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.ferriswheel.v1.Axis x_axis = 8;</code>
     */
    public Builder setXAxis(
        com.ctrip.ferriswheel.proto.v1.Axis.Builder builderForValue) {
      if (xAxisBuilder_ == null) {
        xAxis_ = builderForValue.build();
        onChanged();
      } else {
        xAxisBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.ferriswheel.v1.Axis x_axis = 8;</code>
     */
    public Builder mergeXAxis(com.ctrip.ferriswheel.proto.v1.Axis value) {
      if (xAxisBuilder_ == null) {
        if (xAxis_ != null) {
          xAxis_ =
            com.ctrip.ferriswheel.proto.v1.Axis.newBuilder(xAxis_).mergeFrom(value).buildPartial();
        } else {
          xAxis_ = value;
        }
        onChanged();
      } else {
        xAxisBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.ferriswheel.v1.Axis x_axis = 8;</code>
     */
    public Builder clearXAxis() {
      if (xAxisBuilder_ == null) {
        xAxis_ = null;
        onChanged();
      } else {
        xAxis_ = null;
        xAxisBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.ferriswheel.v1.Axis x_axis = 8;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.Axis.Builder getXAxisBuilder() {
      
      onChanged();
      return getXAxisFieldBuilder().getBuilder();
    }
    /**
     * <code>.ferriswheel.v1.Axis x_axis = 8;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.AxisOrBuilder getXAxisOrBuilder() {
      if (xAxisBuilder_ != null) {
        return xAxisBuilder_.getMessageOrBuilder();
      } else {
        return xAxis_ == null ?
            com.ctrip.ferriswheel.proto.v1.Axis.getDefaultInstance() : xAxis_;
      }
    }
    /**
     * <code>.ferriswheel.v1.Axis x_axis = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ctrip.ferriswheel.proto.v1.Axis, com.ctrip.ferriswheel.proto.v1.Axis.Builder, com.ctrip.ferriswheel.proto.v1.AxisOrBuilder> 
        getXAxisFieldBuilder() {
      if (xAxisBuilder_ == null) {
        xAxisBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ctrip.ferriswheel.proto.v1.Axis, com.ctrip.ferriswheel.proto.v1.Axis.Builder, com.ctrip.ferriswheel.proto.v1.AxisOrBuilder>(
                getXAxis(),
                getParentForChildren(),
                isClean());
        xAxis_ = null;
      }
      return xAxisBuilder_;
    }

    private com.ctrip.ferriswheel.proto.v1.Axis yAxis_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ctrip.ferriswheel.proto.v1.Axis, com.ctrip.ferriswheel.proto.v1.Axis.Builder, com.ctrip.ferriswheel.proto.v1.AxisOrBuilder> yAxisBuilder_;
    /**
     * <code>.ferriswheel.v1.Axis y_axis = 9;</code>
     */
    public boolean hasYAxis() {
      return yAxisBuilder_ != null || yAxis_ != null;
    }
    /**
     * <code>.ferriswheel.v1.Axis y_axis = 9;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.Axis getYAxis() {
      if (yAxisBuilder_ == null) {
        return yAxis_ == null ? com.ctrip.ferriswheel.proto.v1.Axis.getDefaultInstance() : yAxis_;
      } else {
        return yAxisBuilder_.getMessage();
      }
    }
    /**
     * <code>.ferriswheel.v1.Axis y_axis = 9;</code>
     */
    public Builder setYAxis(com.ctrip.ferriswheel.proto.v1.Axis value) {
      if (yAxisBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        yAxis_ = value;
        onChanged();
      } else {
        yAxisBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.ferriswheel.v1.Axis y_axis = 9;</code>
     */
    public Builder setYAxis(
        com.ctrip.ferriswheel.proto.v1.Axis.Builder builderForValue) {
      if (yAxisBuilder_ == null) {
        yAxis_ = builderForValue.build();
        onChanged();
      } else {
        yAxisBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.ferriswheel.v1.Axis y_axis = 9;</code>
     */
    public Builder mergeYAxis(com.ctrip.ferriswheel.proto.v1.Axis value) {
      if (yAxisBuilder_ == null) {
        if (yAxis_ != null) {
          yAxis_ =
            com.ctrip.ferriswheel.proto.v1.Axis.newBuilder(yAxis_).mergeFrom(value).buildPartial();
        } else {
          yAxis_ = value;
        }
        onChanged();
      } else {
        yAxisBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.ferriswheel.v1.Axis y_axis = 9;</code>
     */
    public Builder clearYAxis() {
      if (yAxisBuilder_ == null) {
        yAxis_ = null;
        onChanged();
      } else {
        yAxis_ = null;
        yAxisBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.ferriswheel.v1.Axis y_axis = 9;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.Axis.Builder getYAxisBuilder() {
      
      onChanged();
      return getYAxisFieldBuilder().getBuilder();
    }
    /**
     * <code>.ferriswheel.v1.Axis y_axis = 9;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.AxisOrBuilder getYAxisOrBuilder() {
      if (yAxisBuilder_ != null) {
        return yAxisBuilder_.getMessageOrBuilder();
      } else {
        return yAxis_ == null ?
            com.ctrip.ferriswheel.proto.v1.Axis.getDefaultInstance() : yAxis_;
      }
    }
    /**
     * <code>.ferriswheel.v1.Axis y_axis = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ctrip.ferriswheel.proto.v1.Axis, com.ctrip.ferriswheel.proto.v1.Axis.Builder, com.ctrip.ferriswheel.proto.v1.AxisOrBuilder> 
        getYAxisFieldBuilder() {
      if (yAxisBuilder_ == null) {
        yAxisBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ctrip.ferriswheel.proto.v1.Axis, com.ctrip.ferriswheel.proto.v1.Axis.Builder, com.ctrip.ferriswheel.proto.v1.AxisOrBuilder>(
                getYAxis(),
                getParentForChildren(),
                isClean());
        yAxis_ = null;
      }
      return yAxisBuilder_;
    }

    private com.ctrip.ferriswheel.proto.v1.Axis zAxis_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ctrip.ferriswheel.proto.v1.Axis, com.ctrip.ferriswheel.proto.v1.Axis.Builder, com.ctrip.ferriswheel.proto.v1.AxisOrBuilder> zAxisBuilder_;
    /**
     * <code>.ferriswheel.v1.Axis z_axis = 10;</code>
     */
    public boolean hasZAxis() {
      return zAxisBuilder_ != null || zAxis_ != null;
    }
    /**
     * <code>.ferriswheel.v1.Axis z_axis = 10;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.Axis getZAxis() {
      if (zAxisBuilder_ == null) {
        return zAxis_ == null ? com.ctrip.ferriswheel.proto.v1.Axis.getDefaultInstance() : zAxis_;
      } else {
        return zAxisBuilder_.getMessage();
      }
    }
    /**
     * <code>.ferriswheel.v1.Axis z_axis = 10;</code>
     */
    public Builder setZAxis(com.ctrip.ferriswheel.proto.v1.Axis value) {
      if (zAxisBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        zAxis_ = value;
        onChanged();
      } else {
        zAxisBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.ferriswheel.v1.Axis z_axis = 10;</code>
     */
    public Builder setZAxis(
        com.ctrip.ferriswheel.proto.v1.Axis.Builder builderForValue) {
      if (zAxisBuilder_ == null) {
        zAxis_ = builderForValue.build();
        onChanged();
      } else {
        zAxisBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.ferriswheel.v1.Axis z_axis = 10;</code>
     */
    public Builder mergeZAxis(com.ctrip.ferriswheel.proto.v1.Axis value) {
      if (zAxisBuilder_ == null) {
        if (zAxis_ != null) {
          zAxis_ =
            com.ctrip.ferriswheel.proto.v1.Axis.newBuilder(zAxis_).mergeFrom(value).buildPartial();
        } else {
          zAxis_ = value;
        }
        onChanged();
      } else {
        zAxisBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.ferriswheel.v1.Axis z_axis = 10;</code>
     */
    public Builder clearZAxis() {
      if (zAxisBuilder_ == null) {
        zAxis_ = null;
        onChanged();
      } else {
        zAxis_ = null;
        zAxisBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.ferriswheel.v1.Axis z_axis = 10;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.Axis.Builder getZAxisBuilder() {
      
      onChanged();
      return getZAxisFieldBuilder().getBuilder();
    }
    /**
     * <code>.ferriswheel.v1.Axis z_axis = 10;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.AxisOrBuilder getZAxisOrBuilder() {
      if (zAxisBuilder_ != null) {
        return zAxisBuilder_.getMessageOrBuilder();
      } else {
        return zAxis_ == null ?
            com.ctrip.ferriswheel.proto.v1.Axis.getDefaultInstance() : zAxis_;
      }
    }
    /**
     * <code>.ferriswheel.v1.Axis z_axis = 10;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ctrip.ferriswheel.proto.v1.Axis, com.ctrip.ferriswheel.proto.v1.Axis.Builder, com.ctrip.ferriswheel.proto.v1.AxisOrBuilder> 
        getZAxisFieldBuilder() {
      if (zAxisBuilder_ == null) {
        zAxisBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ctrip.ferriswheel.proto.v1.Axis, com.ctrip.ferriswheel.proto.v1.Axis.Builder, com.ctrip.ferriswheel.proto.v1.AxisOrBuilder>(
                getZAxis(),
                getParentForChildren(),
                isClean());
        zAxis_ = null;
      }
      return zAxisBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ferriswheel.v1.Chart)
  }

  // @@protoc_insertion_point(class_scope:ferriswheel.v1.Chart)
  private static final com.ctrip.ferriswheel.proto.v1.Chart DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ctrip.ferriswheel.proto.v1.Chart();
  }

  public static com.ctrip.ferriswheel.proto.v1.Chart getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Chart>
      PARSER = new com.google.protobuf.AbstractParser<Chart>() {
    @java.lang.Override
    public Chart parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Chart(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Chart> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Chart> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ctrip.ferriswheel.proto.v1.Chart getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

