// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/ctrip/ferriswheel/proto/workbook.proto

package com.ctrip.ferriswheel.proto.v1;

public interface ChartOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ferriswheel.v1.Chart)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string type = 2;</code>
   */
  java.lang.String getType();
  /**
   * <code>string type = 2;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>.ferriswheel.v1.UnionValue title = 3;</code>
   */
  boolean hasTitle();
  /**
   * <code>.ferriswheel.v1.UnionValue title = 3;</code>
   */
  com.ctrip.ferriswheel.proto.v1.UnionValue getTitle();
  /**
   * <code>.ferriswheel.v1.UnionValue title = 3;</code>
   */
  com.ctrip.ferriswheel.proto.v1.UnionValueOrBuilder getTitleOrBuilder();

  /**
   * <code>.ferriswheel.v1.UnionValue categories = 4;</code>
   */
  boolean hasCategories();
  /**
   * <code>.ferriswheel.v1.UnionValue categories = 4;</code>
   */
  com.ctrip.ferriswheel.proto.v1.UnionValue getCategories();
  /**
   * <code>.ferriswheel.v1.UnionValue categories = 4;</code>
   */
  com.ctrip.ferriswheel.proto.v1.UnionValueOrBuilder getCategoriesOrBuilder();

  /**
   * <code>repeated .ferriswheel.v1.Series series = 5;</code>
   */
  java.util.List<com.ctrip.ferriswheel.proto.v1.Series> 
      getSeriesList();
  /**
   * <code>repeated .ferriswheel.v1.Series series = 5;</code>
   */
  com.ctrip.ferriswheel.proto.v1.Series getSeries(int index);
  /**
   * <code>repeated .ferriswheel.v1.Series series = 5;</code>
   */
  int getSeriesCount();
  /**
   * <code>repeated .ferriswheel.v1.Series series = 5;</code>
   */
  java.util.List<? extends com.ctrip.ferriswheel.proto.v1.SeriesOrBuilder> 
      getSeriesOrBuilderList();
  /**
   * <code>repeated .ferriswheel.v1.Series series = 5;</code>
   */
  com.ctrip.ferriswheel.proto.v1.SeriesOrBuilder getSeriesOrBuilder(
      int index);

  /**
   * <code>.ferriswheel.v1.Layout layout = 6;</code>
   */
  boolean hasLayout();
  /**
   * <code>.ferriswheel.v1.Layout layout = 6;</code>
   */
  com.ctrip.ferriswheel.proto.v1.Layout getLayout();
  /**
   * <code>.ferriswheel.v1.Layout layout = 6;</code>
   */
  com.ctrip.ferriswheel.proto.v1.LayoutOrBuilder getLayoutOrBuilder();

  /**
   * <code>.ferriswheel.v1.ChartBinder binder = 7;</code>
   */
  boolean hasBinder();
  /**
   * <code>.ferriswheel.v1.ChartBinder binder = 7;</code>
   */
  com.ctrip.ferriswheel.proto.v1.ChartBinder getBinder();
  /**
   * <code>.ferriswheel.v1.ChartBinder binder = 7;</code>
   */
  com.ctrip.ferriswheel.proto.v1.ChartBinderOrBuilder getBinderOrBuilder();

  /**
   * <code>.ferriswheel.v1.Axis x_axis = 8;</code>
   */
  boolean hasXAxis();
  /**
   * <code>.ferriswheel.v1.Axis x_axis = 8;</code>
   */
  com.ctrip.ferriswheel.proto.v1.Axis getXAxis();
  /**
   * <code>.ferriswheel.v1.Axis x_axis = 8;</code>
   */
  com.ctrip.ferriswheel.proto.v1.AxisOrBuilder getXAxisOrBuilder();

  /**
   * <code>.ferriswheel.v1.Axis y_axis = 9;</code>
   */
  boolean hasYAxis();
  /**
   * <code>.ferriswheel.v1.Axis y_axis = 9;</code>
   */
  com.ctrip.ferriswheel.proto.v1.Axis getYAxis();
  /**
   * <code>.ferriswheel.v1.Axis y_axis = 9;</code>
   */
  com.ctrip.ferriswheel.proto.v1.AxisOrBuilder getYAxisOrBuilder();

  /**
   * <code>.ferriswheel.v1.Axis z_axis = 10;</code>
   */
  boolean hasZAxis();
  /**
   * <code>.ferriswheel.v1.Axis z_axis = 10;</code>
   */
  com.ctrip.ferriswheel.proto.v1.Axis getZAxis();
  /**
   * <code>.ferriswheel.v1.Axis z_axis = 10;</code>
   */
  com.ctrip.ferriswheel.proto.v1.AxisOrBuilder getZAxisOrBuilder();
}
