// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/ctrip/ferriswheel/proto/workbook.proto

package com.ctrip.ferriswheel.proto.v1;

public interface DataQueryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ferriswheel.v1.DataQuery)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string scheme = 1;</code>
   */
  java.lang.String getScheme();
  /**
   * <code>string scheme = 1;</code>
   */
  com.google.protobuf.ByteString
      getSchemeBytes();

  /**
   * <code>repeated .ferriswheel.v1.Parameter params = 2;</code>
   */
  java.util.List<com.ctrip.ferriswheel.proto.v1.Parameter> 
      getParamsList();
  /**
   * <code>repeated .ferriswheel.v1.Parameter params = 2;</code>
   */
  com.ctrip.ferriswheel.proto.v1.Parameter getParams(int index);
  /**
   * <code>repeated .ferriswheel.v1.Parameter params = 2;</code>
   */
  int getParamsCount();
  /**
   * <code>repeated .ferriswheel.v1.Parameter params = 2;</code>
   */
  java.util.List<? extends com.ctrip.ferriswheel.proto.v1.ParameterOrBuilder> 
      getParamsOrBuilderList();
  /**
   * <code>repeated .ferriswheel.v1.Parameter params = 2;</code>
   */
  com.ctrip.ferriswheel.proto.v1.ParameterOrBuilder getParamsOrBuilder(
      int index);
}
