// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/ctrip/ferriswheel/proto/action.proto

package com.ctrip.ferriswheel.proto.v1;

public interface EditRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ferriswheel.v1.EditRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 tx_id = 1;</code>
   */
  long getTxId();

  /**
   * <code>.ferriswheel.v1.Action action = 2;</code>
   */
  boolean hasAction();
  /**
   * <code>.ferriswheel.v1.Action action = 2;</code>
   */
  com.ctrip.ferriswheel.proto.v1.Action getAction();
  /**
   * <code>.ferriswheel.v1.Action action = 2;</code>
   */
  com.ctrip.ferriswheel.proto.v1.ActionOrBuilder getActionOrBuilder();
}
