// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/ctrip/ferriswheel/proto/action.proto

package com.ctrip.ferriswheel.proto.v1;

public interface EditResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ferriswheel.v1.EditResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 tx_id = 1;</code>
   */
  long getTxId();

  /**
   * <code>int32 status_code = 2;</code>
   */
  int getStatusCode();

  /**
   * <code>string message = 3;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 3;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>.ferriswheel.v1.ChangeList changes = 4;</code>
   */
  boolean hasChanges();
  /**
   * <code>.ferriswheel.v1.ChangeList changes = 4;</code>
   */
  com.ctrip.ferriswheel.proto.v1.ChangeList getChanges();
  /**
   * <code>.ferriswheel.v1.ChangeList changes = 4;</code>
   */
  com.ctrip.ferriswheel.proto.v1.ChangeListOrBuilder getChangesOrBuilder();

  /**
   * <code>.ferriswheel.v1.Workbook workbook = 5;</code>
   */
  boolean hasWorkbook();
  /**
   * <code>.ferriswheel.v1.Workbook workbook = 5;</code>
   */
  com.ctrip.ferriswheel.proto.v1.Workbook getWorkbook();
  /**
   * <code>.ferriswheel.v1.Workbook workbook = 5;</code>
   */
  com.ctrip.ferriswheel.proto.v1.WorkbookOrBuilder getWorkbookOrBuilder();

  /**
   * <code>.ferriswheel.v1.Chart suggested_chart = 6;</code>
   */
  boolean hasSuggestedChart();
  /**
   * <code>.ferriswheel.v1.Chart suggested_chart = 6;</code>
   */
  com.ctrip.ferriswheel.proto.v1.Chart getSuggestedChart();
  /**
   * <code>.ferriswheel.v1.Chart suggested_chart = 6;</code>
   */
  com.ctrip.ferriswheel.proto.v1.ChartOrBuilder getSuggestedChartOrBuilder();

  public com.ctrip.ferriswheel.proto.v1.EditResponse.ResponseCase getResponseCase();
}
