// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/ctrip/ferriswheel/proto/workbook.proto

package com.ctrip.ferriswheel.proto.v1;

public interface FormFieldBindingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ferriswheel.v1.FormFieldBinding)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string target = 1;</code>
   */
  java.lang.String getTarget();
  /**
   * <code>string target = 1;</code>
   */
  com.google.protobuf.ByteString
      getTargetBytes();
}
