// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/ctrip/ferriswheel/proto/action.proto

package com.ctrip.ferriswheel.proto.v1;

/**
 * Protobuf type {@code ferriswheel.v1.LayoutAsset}
 */
public  final class LayoutAsset extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ferriswheel.v1.LayoutAsset)
    LayoutAssetOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LayoutAsset.newBuilder() to construct.
  private LayoutAsset(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LayoutAsset() {
    sheetName_ = "";
    assetName_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LayoutAsset(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            sheetName_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            assetName_ = s;
            break;
          }
          case 26: {
            com.ctrip.ferriswheel.proto.v1.Layout.Builder subBuilder = null;
            if (layout_ != null) {
              subBuilder = layout_.toBuilder();
            }
            layout_ = input.readMessage(com.ctrip.ferriswheel.proto.v1.Layout.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(layout_);
              layout_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ctrip.ferriswheel.proto.v1.ActionOuterClass.internal_static_ferriswheel_v1_LayoutAsset_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ctrip.ferriswheel.proto.v1.ActionOuterClass.internal_static_ferriswheel_v1_LayoutAsset_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ctrip.ferriswheel.proto.v1.LayoutAsset.class, com.ctrip.ferriswheel.proto.v1.LayoutAsset.Builder.class);
  }

  public static final int SHEET_NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object sheetName_;
  /**
   * <code>string sheet_name = 1;</code>
   */
  public java.lang.String getSheetName() {
    java.lang.Object ref = sheetName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sheetName_ = s;
      return s;
    }
  }
  /**
   * <code>string sheet_name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getSheetNameBytes() {
    java.lang.Object ref = sheetName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sheetName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ASSET_NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object assetName_;
  /**
   * <code>string asset_name = 2;</code>
   */
  public java.lang.String getAssetName() {
    java.lang.Object ref = assetName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      assetName_ = s;
      return s;
    }
  }
  /**
   * <code>string asset_name = 2;</code>
   */
  public com.google.protobuf.ByteString
      getAssetNameBytes() {
    java.lang.Object ref = assetName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      assetName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LAYOUT_FIELD_NUMBER = 3;
  private com.ctrip.ferriswheel.proto.v1.Layout layout_;
  /**
   * <code>.ferriswheel.v1.Layout layout = 3;</code>
   */
  public boolean hasLayout() {
    return layout_ != null;
  }
  /**
   * <code>.ferriswheel.v1.Layout layout = 3;</code>
   */
  public com.ctrip.ferriswheel.proto.v1.Layout getLayout() {
    return layout_ == null ? com.ctrip.ferriswheel.proto.v1.Layout.getDefaultInstance() : layout_;
  }
  /**
   * <code>.ferriswheel.v1.Layout layout = 3;</code>
   */
  public com.ctrip.ferriswheel.proto.v1.LayoutOrBuilder getLayoutOrBuilder() {
    return getLayout();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getSheetNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sheetName_);
    }
    if (!getAssetNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, assetName_);
    }
    if (layout_ != null) {
      output.writeMessage(3, getLayout());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getSheetNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sheetName_);
    }
    if (!getAssetNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, assetName_);
    }
    if (layout_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getLayout());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ctrip.ferriswheel.proto.v1.LayoutAsset)) {
      return super.equals(obj);
    }
    com.ctrip.ferriswheel.proto.v1.LayoutAsset other = (com.ctrip.ferriswheel.proto.v1.LayoutAsset) obj;

    if (!getSheetName()
        .equals(other.getSheetName())) return false;
    if (!getAssetName()
        .equals(other.getAssetName())) return false;
    if (hasLayout() != other.hasLayout()) return false;
    if (hasLayout()) {
      if (!getLayout()
          .equals(other.getLayout())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SHEET_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getSheetName().hashCode();
    hash = (37 * hash) + ASSET_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getAssetName().hashCode();
    if (hasLayout()) {
      hash = (37 * hash) + LAYOUT_FIELD_NUMBER;
      hash = (53 * hash) + getLayout().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ctrip.ferriswheel.proto.v1.LayoutAsset parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ctrip.ferriswheel.proto.v1.LayoutAsset parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ctrip.ferriswheel.proto.v1.LayoutAsset parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ctrip.ferriswheel.proto.v1.LayoutAsset parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ctrip.ferriswheel.proto.v1.LayoutAsset parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ctrip.ferriswheel.proto.v1.LayoutAsset parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ctrip.ferriswheel.proto.v1.LayoutAsset parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ctrip.ferriswheel.proto.v1.LayoutAsset parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ctrip.ferriswheel.proto.v1.LayoutAsset parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ctrip.ferriswheel.proto.v1.LayoutAsset parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ctrip.ferriswheel.proto.v1.LayoutAsset parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ctrip.ferriswheel.proto.v1.LayoutAsset parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ctrip.ferriswheel.proto.v1.LayoutAsset prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ferriswheel.v1.LayoutAsset}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ferriswheel.v1.LayoutAsset)
      com.ctrip.ferriswheel.proto.v1.LayoutAssetOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ctrip.ferriswheel.proto.v1.ActionOuterClass.internal_static_ferriswheel_v1_LayoutAsset_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ctrip.ferriswheel.proto.v1.ActionOuterClass.internal_static_ferriswheel_v1_LayoutAsset_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ctrip.ferriswheel.proto.v1.LayoutAsset.class, com.ctrip.ferriswheel.proto.v1.LayoutAsset.Builder.class);
    }

    // Construct using com.ctrip.ferriswheel.proto.v1.LayoutAsset.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      sheetName_ = "";

      assetName_ = "";

      if (layoutBuilder_ == null) {
        layout_ = null;
      } else {
        layout_ = null;
        layoutBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ctrip.ferriswheel.proto.v1.ActionOuterClass.internal_static_ferriswheel_v1_LayoutAsset_descriptor;
    }

    @java.lang.Override
    public com.ctrip.ferriswheel.proto.v1.LayoutAsset getDefaultInstanceForType() {
      return com.ctrip.ferriswheel.proto.v1.LayoutAsset.getDefaultInstance();
    }

    @java.lang.Override
    public com.ctrip.ferriswheel.proto.v1.LayoutAsset build() {
      com.ctrip.ferriswheel.proto.v1.LayoutAsset result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ctrip.ferriswheel.proto.v1.LayoutAsset buildPartial() {
      com.ctrip.ferriswheel.proto.v1.LayoutAsset result = new com.ctrip.ferriswheel.proto.v1.LayoutAsset(this);
      result.sheetName_ = sheetName_;
      result.assetName_ = assetName_;
      if (layoutBuilder_ == null) {
        result.layout_ = layout_;
      } else {
        result.layout_ = layoutBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ctrip.ferriswheel.proto.v1.LayoutAsset) {
        return mergeFrom((com.ctrip.ferriswheel.proto.v1.LayoutAsset)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ctrip.ferriswheel.proto.v1.LayoutAsset other) {
      if (other == com.ctrip.ferriswheel.proto.v1.LayoutAsset.getDefaultInstance()) return this;
      if (!other.getSheetName().isEmpty()) {
        sheetName_ = other.sheetName_;
        onChanged();
      }
      if (!other.getAssetName().isEmpty()) {
        assetName_ = other.assetName_;
        onChanged();
      }
      if (other.hasLayout()) {
        mergeLayout(other.getLayout());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ctrip.ferriswheel.proto.v1.LayoutAsset parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ctrip.ferriswheel.proto.v1.LayoutAsset) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object sheetName_ = "";
    /**
     * <code>string sheet_name = 1;</code>
     */
    public java.lang.String getSheetName() {
      java.lang.Object ref = sheetName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sheetName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sheet_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSheetNameBytes() {
      java.lang.Object ref = sheetName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sheetName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sheet_name = 1;</code>
     */
    public Builder setSheetName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sheetName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sheet_name = 1;</code>
     */
    public Builder clearSheetName() {
      
      sheetName_ = getDefaultInstance().getSheetName();
      onChanged();
      return this;
    }
    /**
     * <code>string sheet_name = 1;</code>
     */
    public Builder setSheetNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sheetName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object assetName_ = "";
    /**
     * <code>string asset_name = 2;</code>
     */
    public java.lang.String getAssetName() {
      java.lang.Object ref = assetName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        assetName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string asset_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAssetNameBytes() {
      java.lang.Object ref = assetName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        assetName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string asset_name = 2;</code>
     */
    public Builder setAssetName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      assetName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string asset_name = 2;</code>
     */
    public Builder clearAssetName() {
      
      assetName_ = getDefaultInstance().getAssetName();
      onChanged();
      return this;
    }
    /**
     * <code>string asset_name = 2;</code>
     */
    public Builder setAssetNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      assetName_ = value;
      onChanged();
      return this;
    }

    private com.ctrip.ferriswheel.proto.v1.Layout layout_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ctrip.ferriswheel.proto.v1.Layout, com.ctrip.ferriswheel.proto.v1.Layout.Builder, com.ctrip.ferriswheel.proto.v1.LayoutOrBuilder> layoutBuilder_;
    /**
     * <code>.ferriswheel.v1.Layout layout = 3;</code>
     */
    public boolean hasLayout() {
      return layoutBuilder_ != null || layout_ != null;
    }
    /**
     * <code>.ferriswheel.v1.Layout layout = 3;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.Layout getLayout() {
      if (layoutBuilder_ == null) {
        return layout_ == null ? com.ctrip.ferriswheel.proto.v1.Layout.getDefaultInstance() : layout_;
      } else {
        return layoutBuilder_.getMessage();
      }
    }
    /**
     * <code>.ferriswheel.v1.Layout layout = 3;</code>
     */
    public Builder setLayout(com.ctrip.ferriswheel.proto.v1.Layout value) {
      if (layoutBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        layout_ = value;
        onChanged();
      } else {
        layoutBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.ferriswheel.v1.Layout layout = 3;</code>
     */
    public Builder setLayout(
        com.ctrip.ferriswheel.proto.v1.Layout.Builder builderForValue) {
      if (layoutBuilder_ == null) {
        layout_ = builderForValue.build();
        onChanged();
      } else {
        layoutBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.ferriswheel.v1.Layout layout = 3;</code>
     */
    public Builder mergeLayout(com.ctrip.ferriswheel.proto.v1.Layout value) {
      if (layoutBuilder_ == null) {
        if (layout_ != null) {
          layout_ =
            com.ctrip.ferriswheel.proto.v1.Layout.newBuilder(layout_).mergeFrom(value).buildPartial();
        } else {
          layout_ = value;
        }
        onChanged();
      } else {
        layoutBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.ferriswheel.v1.Layout layout = 3;</code>
     */
    public Builder clearLayout() {
      if (layoutBuilder_ == null) {
        layout_ = null;
        onChanged();
      } else {
        layout_ = null;
        layoutBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.ferriswheel.v1.Layout layout = 3;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.Layout.Builder getLayoutBuilder() {
      
      onChanged();
      return getLayoutFieldBuilder().getBuilder();
    }
    /**
     * <code>.ferriswheel.v1.Layout layout = 3;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.LayoutOrBuilder getLayoutOrBuilder() {
      if (layoutBuilder_ != null) {
        return layoutBuilder_.getMessageOrBuilder();
      } else {
        return layout_ == null ?
            com.ctrip.ferriswheel.proto.v1.Layout.getDefaultInstance() : layout_;
      }
    }
    /**
     * <code>.ferriswheel.v1.Layout layout = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ctrip.ferriswheel.proto.v1.Layout, com.ctrip.ferriswheel.proto.v1.Layout.Builder, com.ctrip.ferriswheel.proto.v1.LayoutOrBuilder> 
        getLayoutFieldBuilder() {
      if (layoutBuilder_ == null) {
        layoutBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ctrip.ferriswheel.proto.v1.Layout, com.ctrip.ferriswheel.proto.v1.Layout.Builder, com.ctrip.ferriswheel.proto.v1.LayoutOrBuilder>(
                getLayout(),
                getParentForChildren(),
                isClean());
        layout_ = null;
      }
      return layoutBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ferriswheel.v1.LayoutAsset)
  }

  // @@protoc_insertion_point(class_scope:ferriswheel.v1.LayoutAsset)
  private static final com.ctrip.ferriswheel.proto.v1.LayoutAsset DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ctrip.ferriswheel.proto.v1.LayoutAsset();
  }

  public static com.ctrip.ferriswheel.proto.v1.LayoutAsset getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LayoutAsset>
      PARSER = new com.google.protobuf.AbstractParser<LayoutAsset>() {
    @java.lang.Override
    public LayoutAsset parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LayoutAsset(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LayoutAsset> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LayoutAsset> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ctrip.ferriswheel.proto.v1.LayoutAsset getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

