// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/ctrip/ferriswheel/proto/workbook.proto

package com.ctrip.ferriswheel.proto.v1;

/**
 * Protobuf type {@code ferriswheel.v1.Layout}
 */
public  final class Layout extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ferriswheel.v1.Layout)
    LayoutOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Layout.newBuilder() to construct.
  private Layout(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Layout() {
    display_ = 0;
    width_ = 0;
    height_ = 0;
    align_ = 0;
    verticalAlign_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Layout(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            display_ = rawValue;
            break;
          }
          case 16: {

            width_ = input.readInt32();
            break;
          }
          case 24: {

            height_ = input.readInt32();
            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            align_ = rawValue;
            break;
          }
          case 40: {
            int rawValue = input.readEnum();

            verticalAlign_ = rawValue;
            break;
          }
          case 50: {
            com.ctrip.ferriswheel.proto.v1.Grid.Builder subBuilder = null;
            if (grid_ != null) {
              subBuilder = grid_.toBuilder();
            }
            grid_ = input.readMessage(com.ctrip.ferriswheel.proto.v1.Grid.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(grid_);
              grid_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ctrip.ferriswheel.proto.v1.WorkbookOuterClass.internal_static_ferriswheel_v1_Layout_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ctrip.ferriswheel.proto.v1.WorkbookOuterClass.internal_static_ferriswheel_v1_Layout_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ctrip.ferriswheel.proto.v1.Layout.class, com.ctrip.ferriswheel.proto.v1.Layout.Builder.class);
  }

  public static final int DISPLAY_FIELD_NUMBER = 1;
  private int display_;
  /**
   * <code>.ferriswheel.v1.Display display = 1;</code>
   */
  public int getDisplayValue() {
    return display_;
  }
  /**
   * <code>.ferriswheel.v1.Display display = 1;</code>
   */
  public com.ctrip.ferriswheel.proto.v1.Display getDisplay() {
    @SuppressWarnings("deprecation")
    com.ctrip.ferriswheel.proto.v1.Display result = com.ctrip.ferriswheel.proto.v1.Display.valueOf(display_);
    return result == null ? com.ctrip.ferriswheel.proto.v1.Display.UNRECOGNIZED : result;
  }

  public static final int WIDTH_FIELD_NUMBER = 2;
  private int width_;
  /**
   * <code>int32 width = 2;</code>
   */
  public int getWidth() {
    return width_;
  }

  public static final int HEIGHT_FIELD_NUMBER = 3;
  private int height_;
  /**
   * <code>int32 height = 3;</code>
   */
  public int getHeight() {
    return height_;
  }

  public static final int ALIGN_FIELD_NUMBER = 4;
  private int align_;
  /**
   * <code>.ferriswheel.v1.Placement align = 4;</code>
   */
  public int getAlignValue() {
    return align_;
  }
  /**
   * <code>.ferriswheel.v1.Placement align = 4;</code>
   */
  public com.ctrip.ferriswheel.proto.v1.Placement getAlign() {
    @SuppressWarnings("deprecation")
    com.ctrip.ferriswheel.proto.v1.Placement result = com.ctrip.ferriswheel.proto.v1.Placement.valueOf(align_);
    return result == null ? com.ctrip.ferriswheel.proto.v1.Placement.UNRECOGNIZED : result;
  }

  public static final int VERTICAL_ALIGN_FIELD_NUMBER = 5;
  private int verticalAlign_;
  /**
   * <code>.ferriswheel.v1.Placement vertical_align = 5;</code>
   */
  public int getVerticalAlignValue() {
    return verticalAlign_;
  }
  /**
   * <code>.ferriswheel.v1.Placement vertical_align = 5;</code>
   */
  public com.ctrip.ferriswheel.proto.v1.Placement getVerticalAlign() {
    @SuppressWarnings("deprecation")
    com.ctrip.ferriswheel.proto.v1.Placement result = com.ctrip.ferriswheel.proto.v1.Placement.valueOf(verticalAlign_);
    return result == null ? com.ctrip.ferriswheel.proto.v1.Placement.UNRECOGNIZED : result;
  }

  public static final int GRID_FIELD_NUMBER = 6;
  private com.ctrip.ferriswheel.proto.v1.Grid grid_;
  /**
   * <code>.ferriswheel.v1.Grid grid = 6;</code>
   */
  public boolean hasGrid() {
    return grid_ != null;
  }
  /**
   * <code>.ferriswheel.v1.Grid grid = 6;</code>
   */
  public com.ctrip.ferriswheel.proto.v1.Grid getGrid() {
    return grid_ == null ? com.ctrip.ferriswheel.proto.v1.Grid.getDefaultInstance() : grid_;
  }
  /**
   * <code>.ferriswheel.v1.Grid grid = 6;</code>
   */
  public com.ctrip.ferriswheel.proto.v1.GridOrBuilder getGridOrBuilder() {
    return getGrid();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (display_ != com.ctrip.ferriswheel.proto.v1.Display.DISP_UNSET.getNumber()) {
      output.writeEnum(1, display_);
    }
    if (width_ != 0) {
      output.writeInt32(2, width_);
    }
    if (height_ != 0) {
      output.writeInt32(3, height_);
    }
    if (align_ != com.ctrip.ferriswheel.proto.v1.Placement.PLCMT_UNSET.getNumber()) {
      output.writeEnum(4, align_);
    }
    if (verticalAlign_ != com.ctrip.ferriswheel.proto.v1.Placement.PLCMT_UNSET.getNumber()) {
      output.writeEnum(5, verticalAlign_);
    }
    if (grid_ != null) {
      output.writeMessage(6, getGrid());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (display_ != com.ctrip.ferriswheel.proto.v1.Display.DISP_UNSET.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, display_);
    }
    if (width_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, width_);
    }
    if (height_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, height_);
    }
    if (align_ != com.ctrip.ferriswheel.proto.v1.Placement.PLCMT_UNSET.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, align_);
    }
    if (verticalAlign_ != com.ctrip.ferriswheel.proto.v1.Placement.PLCMT_UNSET.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, verticalAlign_);
    }
    if (grid_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getGrid());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ctrip.ferriswheel.proto.v1.Layout)) {
      return super.equals(obj);
    }
    com.ctrip.ferriswheel.proto.v1.Layout other = (com.ctrip.ferriswheel.proto.v1.Layout) obj;

    boolean result = true;
    result = result && display_ == other.display_;
    result = result && (getWidth()
        == other.getWidth());
    result = result && (getHeight()
        == other.getHeight());
    result = result && align_ == other.align_;
    result = result && verticalAlign_ == other.verticalAlign_;
    result = result && (hasGrid() == other.hasGrid());
    if (hasGrid()) {
      result = result && getGrid()
          .equals(other.getGrid());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DISPLAY_FIELD_NUMBER;
    hash = (53 * hash) + display_;
    hash = (37 * hash) + WIDTH_FIELD_NUMBER;
    hash = (53 * hash) + getWidth();
    hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + getHeight();
    hash = (37 * hash) + ALIGN_FIELD_NUMBER;
    hash = (53 * hash) + align_;
    hash = (37 * hash) + VERTICAL_ALIGN_FIELD_NUMBER;
    hash = (53 * hash) + verticalAlign_;
    if (hasGrid()) {
      hash = (37 * hash) + GRID_FIELD_NUMBER;
      hash = (53 * hash) + getGrid().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ctrip.ferriswheel.proto.v1.Layout parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ctrip.ferriswheel.proto.v1.Layout parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ctrip.ferriswheel.proto.v1.Layout parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ctrip.ferriswheel.proto.v1.Layout parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ctrip.ferriswheel.proto.v1.Layout parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ctrip.ferriswheel.proto.v1.Layout parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ctrip.ferriswheel.proto.v1.Layout parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ctrip.ferriswheel.proto.v1.Layout parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ctrip.ferriswheel.proto.v1.Layout parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ctrip.ferriswheel.proto.v1.Layout parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ctrip.ferriswheel.proto.v1.Layout parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ctrip.ferriswheel.proto.v1.Layout parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ctrip.ferriswheel.proto.v1.Layout prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ferriswheel.v1.Layout}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ferriswheel.v1.Layout)
      com.ctrip.ferriswheel.proto.v1.LayoutOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ctrip.ferriswheel.proto.v1.WorkbookOuterClass.internal_static_ferriswheel_v1_Layout_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ctrip.ferriswheel.proto.v1.WorkbookOuterClass.internal_static_ferriswheel_v1_Layout_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ctrip.ferriswheel.proto.v1.Layout.class, com.ctrip.ferriswheel.proto.v1.Layout.Builder.class);
    }

    // Construct using com.ctrip.ferriswheel.proto.v1.Layout.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      display_ = 0;

      width_ = 0;

      height_ = 0;

      align_ = 0;

      verticalAlign_ = 0;

      if (gridBuilder_ == null) {
        grid_ = null;
      } else {
        grid_ = null;
        gridBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ctrip.ferriswheel.proto.v1.WorkbookOuterClass.internal_static_ferriswheel_v1_Layout_descriptor;
    }

    @java.lang.Override
    public com.ctrip.ferriswheel.proto.v1.Layout getDefaultInstanceForType() {
      return com.ctrip.ferriswheel.proto.v1.Layout.getDefaultInstance();
    }

    @java.lang.Override
    public com.ctrip.ferriswheel.proto.v1.Layout build() {
      com.ctrip.ferriswheel.proto.v1.Layout result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ctrip.ferriswheel.proto.v1.Layout buildPartial() {
      com.ctrip.ferriswheel.proto.v1.Layout result = new com.ctrip.ferriswheel.proto.v1.Layout(this);
      result.display_ = display_;
      result.width_ = width_;
      result.height_ = height_;
      result.align_ = align_;
      result.verticalAlign_ = verticalAlign_;
      if (gridBuilder_ == null) {
        result.grid_ = grid_;
      } else {
        result.grid_ = gridBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ctrip.ferriswheel.proto.v1.Layout) {
        return mergeFrom((com.ctrip.ferriswheel.proto.v1.Layout)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ctrip.ferriswheel.proto.v1.Layout other) {
      if (other == com.ctrip.ferriswheel.proto.v1.Layout.getDefaultInstance()) return this;
      if (other.display_ != 0) {
        setDisplayValue(other.getDisplayValue());
      }
      if (other.getWidth() != 0) {
        setWidth(other.getWidth());
      }
      if (other.getHeight() != 0) {
        setHeight(other.getHeight());
      }
      if (other.align_ != 0) {
        setAlignValue(other.getAlignValue());
      }
      if (other.verticalAlign_ != 0) {
        setVerticalAlignValue(other.getVerticalAlignValue());
      }
      if (other.hasGrid()) {
        mergeGrid(other.getGrid());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ctrip.ferriswheel.proto.v1.Layout parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ctrip.ferriswheel.proto.v1.Layout) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int display_ = 0;
    /**
     * <code>.ferriswheel.v1.Display display = 1;</code>
     */
    public int getDisplayValue() {
      return display_;
    }
    /**
     * <code>.ferriswheel.v1.Display display = 1;</code>
     */
    public Builder setDisplayValue(int value) {
      display_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.ferriswheel.v1.Display display = 1;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.Display getDisplay() {
      @SuppressWarnings("deprecation")
      com.ctrip.ferriswheel.proto.v1.Display result = com.ctrip.ferriswheel.proto.v1.Display.valueOf(display_);
      return result == null ? com.ctrip.ferriswheel.proto.v1.Display.UNRECOGNIZED : result;
    }
    /**
     * <code>.ferriswheel.v1.Display display = 1;</code>
     */
    public Builder setDisplay(com.ctrip.ferriswheel.proto.v1.Display value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      display_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.ferriswheel.v1.Display display = 1;</code>
     */
    public Builder clearDisplay() {
      
      display_ = 0;
      onChanged();
      return this;
    }

    private int width_ ;
    /**
     * <code>int32 width = 2;</code>
     */
    public int getWidth() {
      return width_;
    }
    /**
     * <code>int32 width = 2;</code>
     */
    public Builder setWidth(int value) {
      
      width_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 width = 2;</code>
     */
    public Builder clearWidth() {
      
      width_ = 0;
      onChanged();
      return this;
    }

    private int height_ ;
    /**
     * <code>int32 height = 3;</code>
     */
    public int getHeight() {
      return height_;
    }
    /**
     * <code>int32 height = 3;</code>
     */
    public Builder setHeight(int value) {
      
      height_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 height = 3;</code>
     */
    public Builder clearHeight() {
      
      height_ = 0;
      onChanged();
      return this;
    }

    private int align_ = 0;
    /**
     * <code>.ferriswheel.v1.Placement align = 4;</code>
     */
    public int getAlignValue() {
      return align_;
    }
    /**
     * <code>.ferriswheel.v1.Placement align = 4;</code>
     */
    public Builder setAlignValue(int value) {
      align_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.ferriswheel.v1.Placement align = 4;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.Placement getAlign() {
      @SuppressWarnings("deprecation")
      com.ctrip.ferriswheel.proto.v1.Placement result = com.ctrip.ferriswheel.proto.v1.Placement.valueOf(align_);
      return result == null ? com.ctrip.ferriswheel.proto.v1.Placement.UNRECOGNIZED : result;
    }
    /**
     * <code>.ferriswheel.v1.Placement align = 4;</code>
     */
    public Builder setAlign(com.ctrip.ferriswheel.proto.v1.Placement value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      align_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.ferriswheel.v1.Placement align = 4;</code>
     */
    public Builder clearAlign() {
      
      align_ = 0;
      onChanged();
      return this;
    }

    private int verticalAlign_ = 0;
    /**
     * <code>.ferriswheel.v1.Placement vertical_align = 5;</code>
     */
    public int getVerticalAlignValue() {
      return verticalAlign_;
    }
    /**
     * <code>.ferriswheel.v1.Placement vertical_align = 5;</code>
     */
    public Builder setVerticalAlignValue(int value) {
      verticalAlign_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.ferriswheel.v1.Placement vertical_align = 5;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.Placement getVerticalAlign() {
      @SuppressWarnings("deprecation")
      com.ctrip.ferriswheel.proto.v1.Placement result = com.ctrip.ferriswheel.proto.v1.Placement.valueOf(verticalAlign_);
      return result == null ? com.ctrip.ferriswheel.proto.v1.Placement.UNRECOGNIZED : result;
    }
    /**
     * <code>.ferriswheel.v1.Placement vertical_align = 5;</code>
     */
    public Builder setVerticalAlign(com.ctrip.ferriswheel.proto.v1.Placement value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      verticalAlign_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.ferriswheel.v1.Placement vertical_align = 5;</code>
     */
    public Builder clearVerticalAlign() {
      
      verticalAlign_ = 0;
      onChanged();
      return this;
    }

    private com.ctrip.ferriswheel.proto.v1.Grid grid_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ctrip.ferriswheel.proto.v1.Grid, com.ctrip.ferriswheel.proto.v1.Grid.Builder, com.ctrip.ferriswheel.proto.v1.GridOrBuilder> gridBuilder_;
    /**
     * <code>.ferriswheel.v1.Grid grid = 6;</code>
     */
    public boolean hasGrid() {
      return gridBuilder_ != null || grid_ != null;
    }
    /**
     * <code>.ferriswheel.v1.Grid grid = 6;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.Grid getGrid() {
      if (gridBuilder_ == null) {
        return grid_ == null ? com.ctrip.ferriswheel.proto.v1.Grid.getDefaultInstance() : grid_;
      } else {
        return gridBuilder_.getMessage();
      }
    }
    /**
     * <code>.ferriswheel.v1.Grid grid = 6;</code>
     */
    public Builder setGrid(com.ctrip.ferriswheel.proto.v1.Grid value) {
      if (gridBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        grid_ = value;
        onChanged();
      } else {
        gridBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.ferriswheel.v1.Grid grid = 6;</code>
     */
    public Builder setGrid(
        com.ctrip.ferriswheel.proto.v1.Grid.Builder builderForValue) {
      if (gridBuilder_ == null) {
        grid_ = builderForValue.build();
        onChanged();
      } else {
        gridBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.ferriswheel.v1.Grid grid = 6;</code>
     */
    public Builder mergeGrid(com.ctrip.ferriswheel.proto.v1.Grid value) {
      if (gridBuilder_ == null) {
        if (grid_ != null) {
          grid_ =
            com.ctrip.ferriswheel.proto.v1.Grid.newBuilder(grid_).mergeFrom(value).buildPartial();
        } else {
          grid_ = value;
        }
        onChanged();
      } else {
        gridBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.ferriswheel.v1.Grid grid = 6;</code>
     */
    public Builder clearGrid() {
      if (gridBuilder_ == null) {
        grid_ = null;
        onChanged();
      } else {
        grid_ = null;
        gridBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.ferriswheel.v1.Grid grid = 6;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.Grid.Builder getGridBuilder() {
      
      onChanged();
      return getGridFieldBuilder().getBuilder();
    }
    /**
     * <code>.ferriswheel.v1.Grid grid = 6;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.GridOrBuilder getGridOrBuilder() {
      if (gridBuilder_ != null) {
        return gridBuilder_.getMessageOrBuilder();
      } else {
        return grid_ == null ?
            com.ctrip.ferriswheel.proto.v1.Grid.getDefaultInstance() : grid_;
      }
    }
    /**
     * <code>.ferriswheel.v1.Grid grid = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ctrip.ferriswheel.proto.v1.Grid, com.ctrip.ferriswheel.proto.v1.Grid.Builder, com.ctrip.ferriswheel.proto.v1.GridOrBuilder> 
        getGridFieldBuilder() {
      if (gridBuilder_ == null) {
        gridBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ctrip.ferriswheel.proto.v1.Grid, com.ctrip.ferriswheel.proto.v1.Grid.Builder, com.ctrip.ferriswheel.proto.v1.GridOrBuilder>(
                getGrid(),
                getParentForChildren(),
                isClean());
        grid_ = null;
      }
      return gridBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ferriswheel.v1.Layout)
  }

  // @@protoc_insertion_point(class_scope:ferriswheel.v1.Layout)
  private static final com.ctrip.ferriswheel.proto.v1.Layout DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ctrip.ferriswheel.proto.v1.Layout();
  }

  public static com.ctrip.ferriswheel.proto.v1.Layout getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Layout>
      PARSER = new com.google.protobuf.AbstractParser<Layout>() {
    @java.lang.Override
    public Layout parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Layout(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Layout> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Layout> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ctrip.ferriswheel.proto.v1.Layout getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

