// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/ctrip/ferriswheel/proto/workbook.proto

package com.ctrip.ferriswheel.proto.v1;

public interface PivotFieldOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ferriswheel.v1.PivotField)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string field = 1;</code>
   */
  java.lang.String getField();
  /**
   * <code>string field = 1;</code>
   */
  com.google.protobuf.ByteString
      getFieldBytes();

  /**
   * <code>string format = 2;</code>
   */
  java.lang.String getFormat();
  /**
   * <code>string format = 2;</code>
   */
  com.google.protobuf.ByteString
      getFormatBytes();
}
