// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/ctrip/ferriswheel/proto/workbook.proto

package com.ctrip.ferriswheel.proto.v1;

public interface QueryTemplateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ferriswheel.v1.QueryTemplate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string scheme = 1;</code>
   */
  java.lang.String getScheme();
  /**
   * <code>string scheme = 1;</code>
   */
  com.google.protobuf.ByteString
      getSchemeBytes();

  /**
   * <code>repeated .ferriswheel.v1.Parameter builtin_params = 2;</code>
   */
  java.util.List<com.ctrip.ferriswheel.proto.v1.Parameter> 
      getBuiltinParamsList();
  /**
   * <code>repeated .ferriswheel.v1.Parameter builtin_params = 2;</code>
   */
  com.ctrip.ferriswheel.proto.v1.Parameter getBuiltinParams(int index);
  /**
   * <code>repeated .ferriswheel.v1.Parameter builtin_params = 2;</code>
   */
  int getBuiltinParamsCount();
  /**
   * <code>repeated .ferriswheel.v1.Parameter builtin_params = 2;</code>
   */
  java.util.List<? extends com.ctrip.ferriswheel.proto.v1.ParameterOrBuilder> 
      getBuiltinParamsOrBuilderList();
  /**
   * <code>repeated .ferriswheel.v1.Parameter builtin_params = 2;</code>
   */
  com.ctrip.ferriswheel.proto.v1.ParameterOrBuilder getBuiltinParamsOrBuilder(
      int index);
}
