// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/ctrip/ferriswheel/proto/action.proto

package com.ctrip.ferriswheel.proto.v1;

public interface RenameAssetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ferriswheel.v1.RenameAsset)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sheet_name = 1;</code>
   */
  java.lang.String getSheetName();
  /**
   * <code>string sheet_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getSheetNameBytes();

  /**
   * <code>string old_asset_name = 2;</code>
   */
  java.lang.String getOldAssetName();
  /**
   * <code>string old_asset_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getOldAssetNameBytes();

  /**
   * <code>string new_asset_name = 3;</code>
   */
  java.lang.String getNewAssetName();
  /**
   * <code>string new_asset_name = 3;</code>
   */
  com.google.protobuf.ByteString
      getNewAssetNameBytes();
}
