// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/ctrip/ferriswheel/proto/action.proto

package com.ctrip.ferriswheel.proto.v1;

public interface RenameSheetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ferriswheel.v1.RenameSheet)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string old_sheet_name = 1;</code>
   */
  java.lang.String getOldSheetName();
  /**
   * <code>string old_sheet_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getOldSheetNameBytes();

  /**
   * <code>string new_sheet_name = 2;</code>
   */
  java.lang.String getNewSheetName();
  /**
   * <code>string new_sheet_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNewSheetNameBytes();
}
