// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/ctrip/ferriswheel/proto/workbook.proto

package com.ctrip.ferriswheel.proto.v1;

public interface SheetAssetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ferriswheel.v1.SheetAsset)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ferriswheel.v1.Table table = 1;</code>
   */
  boolean hasTable();
  /**
   * <code>.ferriswheel.v1.Table table = 1;</code>
   */
  com.ctrip.ferriswheel.proto.v1.Table getTable();
  /**
   * <code>.ferriswheel.v1.Table table = 1;</code>
   */
  com.ctrip.ferriswheel.proto.v1.TableOrBuilder getTableOrBuilder();

  /**
   * <code>.ferriswheel.v1.Chart chart = 2;</code>
   */
  boolean hasChart();
  /**
   * <code>.ferriswheel.v1.Chart chart = 2;</code>
   */
  com.ctrip.ferriswheel.proto.v1.Chart getChart();
  /**
   * <code>.ferriswheel.v1.Chart chart = 2;</code>
   */
  com.ctrip.ferriswheel.proto.v1.ChartOrBuilder getChartOrBuilder();

  /**
   * <code>.ferriswheel.v1.Text text = 3;</code>
   */
  boolean hasText();
  /**
   * <code>.ferriswheel.v1.Text text = 3;</code>
   */
  com.ctrip.ferriswheel.proto.v1.Text getText();
  /**
   * <code>.ferriswheel.v1.Text text = 3;</code>
   */
  com.ctrip.ferriswheel.proto.v1.TextOrBuilder getTextOrBuilder();

  /**
   * <code>.ferriswheel.v1.Form form = 4;</code>
   */
  boolean hasForm();
  /**
   * <code>.ferriswheel.v1.Form form = 4;</code>
   */
  com.ctrip.ferriswheel.proto.v1.Form getForm();
  /**
   * <code>.ferriswheel.v1.Form form = 4;</code>
   */
  com.ctrip.ferriswheel.proto.v1.FormOrBuilder getFormOrBuilder();

  public com.ctrip.ferriswheel.proto.v1.SheetAsset.AssetCase getAssetCase();
}
