// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/ctrip/ferriswheel/proto/workbook.proto

package com.ctrip.ferriswheel.proto.v1;

public interface SheetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ferriswheel.v1.Sheet)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>repeated .ferriswheel.v1.SheetAsset assets = 2;</code>
   */
  java.util.List<com.ctrip.ferriswheel.proto.v1.SheetAsset> 
      getAssetsList();
  /**
   * <code>repeated .ferriswheel.v1.SheetAsset assets = 2;</code>
   */
  com.ctrip.ferriswheel.proto.v1.SheetAsset getAssets(int index);
  /**
   * <code>repeated .ferriswheel.v1.SheetAsset assets = 2;</code>
   */
  int getAssetsCount();
  /**
   * <code>repeated .ferriswheel.v1.SheetAsset assets = 2;</code>
   */
  java.util.List<? extends com.ctrip.ferriswheel.proto.v1.SheetAssetOrBuilder> 
      getAssetsOrBuilderList();
  /**
   * <code>repeated .ferriswheel.v1.SheetAsset assets = 2;</code>
   */
  com.ctrip.ferriswheel.proto.v1.SheetAssetOrBuilder getAssetsOrBuilder(
      int index);

  /**
   * <code>.ferriswheel.v1.Layout layout = 3;</code>
   */
  boolean hasLayout();
  /**
   * <code>.ferriswheel.v1.Layout layout = 3;</code>
   */
  com.ctrip.ferriswheel.proto.v1.Layout getLayout();
  /**
   * <code>.ferriswheel.v1.Layout layout = 3;</code>
   */
  com.ctrip.ferriswheel.proto.v1.LayoutOrBuilder getLayoutOrBuilder();
}
