// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/ctrip/ferriswheel/proto/workbook.proto

package com.ctrip.ferriswheel.proto.v1;

/**
 * Protobuf type {@code ferriswheel.v1.Table}
 */
public  final class Table extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ferriswheel.v1.Table)
    TableOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Table.newBuilder() to construct.
  private Table(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Table() {
    name_ = "";
    rows_ = java.util.Collections.emptyList();
    rowHeaders_ = java.util.Collections.emptyList();
    columnHeaders_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Table(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              rows_ = new java.util.ArrayList<com.ctrip.ferriswheel.proto.v1.Row>();
              mutable_bitField0_ |= 0x00000002;
            }
            rows_.add(
                input.readMessage(com.ctrip.ferriswheel.proto.v1.Row.parser(), extensionRegistry));
            break;
          }
          case 26: {
            com.ctrip.ferriswheel.proto.v1.TableAutomaton.Builder subBuilder = null;
            if (automaton_ != null) {
              subBuilder = automaton_.toBuilder();
            }
            automaton_ = input.readMessage(com.ctrip.ferriswheel.proto.v1.TableAutomaton.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(automaton_);
              automaton_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            com.ctrip.ferriswheel.proto.v1.Layout.Builder subBuilder = null;
            if (layout_ != null) {
              subBuilder = layout_.toBuilder();
            }
            layout_ = input.readMessage(com.ctrip.ferriswheel.proto.v1.Layout.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(layout_);
              layout_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000010) != 0)) {
              rowHeaders_ = new java.util.ArrayList<com.ctrip.ferriswheel.proto.v1.Header>();
              mutable_bitField0_ |= 0x00000010;
            }
            rowHeaders_.add(
                input.readMessage(com.ctrip.ferriswheel.proto.v1.Header.parser(), extensionRegistry));
            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000020) != 0)) {
              columnHeaders_ = new java.util.ArrayList<com.ctrip.ferriswheel.proto.v1.Header>();
              mutable_bitField0_ |= 0x00000020;
            }
            columnHeaders_.add(
                input.readMessage(com.ctrip.ferriswheel.proto.v1.Header.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        rows_ = java.util.Collections.unmodifiableList(rows_);
      }
      if (((mutable_bitField0_ & 0x00000010) != 0)) {
        rowHeaders_ = java.util.Collections.unmodifiableList(rowHeaders_);
      }
      if (((mutable_bitField0_ & 0x00000020) != 0)) {
        columnHeaders_ = java.util.Collections.unmodifiableList(columnHeaders_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ctrip.ferriswheel.proto.v1.WorkbookOuterClass.internal_static_ferriswheel_v1_Table_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ctrip.ferriswheel.proto.v1.WorkbookOuterClass.internal_static_ferriswheel_v1_Table_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ctrip.ferriswheel.proto.v1.Table.class, com.ctrip.ferriswheel.proto.v1.Table.Builder.class);
  }

  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 1;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ROWS_FIELD_NUMBER = 2;
  private java.util.List<com.ctrip.ferriswheel.proto.v1.Row> rows_;
  /**
   * <code>repeated .ferriswheel.v1.Row rows = 2;</code>
   */
  public java.util.List<com.ctrip.ferriswheel.proto.v1.Row> getRowsList() {
    return rows_;
  }
  /**
   * <code>repeated .ferriswheel.v1.Row rows = 2;</code>
   */
  public java.util.List<? extends com.ctrip.ferriswheel.proto.v1.RowOrBuilder> 
      getRowsOrBuilderList() {
    return rows_;
  }
  /**
   * <code>repeated .ferriswheel.v1.Row rows = 2;</code>
   */
  public int getRowsCount() {
    return rows_.size();
  }
  /**
   * <code>repeated .ferriswheel.v1.Row rows = 2;</code>
   */
  public com.ctrip.ferriswheel.proto.v1.Row getRows(int index) {
    return rows_.get(index);
  }
  /**
   * <code>repeated .ferriswheel.v1.Row rows = 2;</code>
   */
  public com.ctrip.ferriswheel.proto.v1.RowOrBuilder getRowsOrBuilder(
      int index) {
    return rows_.get(index);
  }

  public static final int AUTOMATON_FIELD_NUMBER = 3;
  private com.ctrip.ferriswheel.proto.v1.TableAutomaton automaton_;
  /**
   * <code>.ferriswheel.v1.TableAutomaton automaton = 3;</code>
   */
  public boolean hasAutomaton() {
    return automaton_ != null;
  }
  /**
   * <code>.ferriswheel.v1.TableAutomaton automaton = 3;</code>
   */
  public com.ctrip.ferriswheel.proto.v1.TableAutomaton getAutomaton() {
    return automaton_ == null ? com.ctrip.ferriswheel.proto.v1.TableAutomaton.getDefaultInstance() : automaton_;
  }
  /**
   * <code>.ferriswheel.v1.TableAutomaton automaton = 3;</code>
   */
  public com.ctrip.ferriswheel.proto.v1.TableAutomatonOrBuilder getAutomatonOrBuilder() {
    return getAutomaton();
  }

  public static final int LAYOUT_FIELD_NUMBER = 4;
  private com.ctrip.ferriswheel.proto.v1.Layout layout_;
  /**
   * <code>.ferriswheel.v1.Layout layout = 4;</code>
   */
  public boolean hasLayout() {
    return layout_ != null;
  }
  /**
   * <code>.ferriswheel.v1.Layout layout = 4;</code>
   */
  public com.ctrip.ferriswheel.proto.v1.Layout getLayout() {
    return layout_ == null ? com.ctrip.ferriswheel.proto.v1.Layout.getDefaultInstance() : layout_;
  }
  /**
   * <code>.ferriswheel.v1.Layout layout = 4;</code>
   */
  public com.ctrip.ferriswheel.proto.v1.LayoutOrBuilder getLayoutOrBuilder() {
    return getLayout();
  }

  public static final int ROW_HEADERS_FIELD_NUMBER = 5;
  private java.util.List<com.ctrip.ferriswheel.proto.v1.Header> rowHeaders_;
  /**
   * <code>repeated .ferriswheel.v1.Header row_headers = 5;</code>
   */
  public java.util.List<com.ctrip.ferriswheel.proto.v1.Header> getRowHeadersList() {
    return rowHeaders_;
  }
  /**
   * <code>repeated .ferriswheel.v1.Header row_headers = 5;</code>
   */
  public java.util.List<? extends com.ctrip.ferriswheel.proto.v1.HeaderOrBuilder> 
      getRowHeadersOrBuilderList() {
    return rowHeaders_;
  }
  /**
   * <code>repeated .ferriswheel.v1.Header row_headers = 5;</code>
   */
  public int getRowHeadersCount() {
    return rowHeaders_.size();
  }
  /**
   * <code>repeated .ferriswheel.v1.Header row_headers = 5;</code>
   */
  public com.ctrip.ferriswheel.proto.v1.Header getRowHeaders(int index) {
    return rowHeaders_.get(index);
  }
  /**
   * <code>repeated .ferriswheel.v1.Header row_headers = 5;</code>
   */
  public com.ctrip.ferriswheel.proto.v1.HeaderOrBuilder getRowHeadersOrBuilder(
      int index) {
    return rowHeaders_.get(index);
  }

  public static final int COLUMN_HEADERS_FIELD_NUMBER = 6;
  private java.util.List<com.ctrip.ferriswheel.proto.v1.Header> columnHeaders_;
  /**
   * <code>repeated .ferriswheel.v1.Header column_headers = 6;</code>
   */
  public java.util.List<com.ctrip.ferriswheel.proto.v1.Header> getColumnHeadersList() {
    return columnHeaders_;
  }
  /**
   * <code>repeated .ferriswheel.v1.Header column_headers = 6;</code>
   */
  public java.util.List<? extends com.ctrip.ferriswheel.proto.v1.HeaderOrBuilder> 
      getColumnHeadersOrBuilderList() {
    return columnHeaders_;
  }
  /**
   * <code>repeated .ferriswheel.v1.Header column_headers = 6;</code>
   */
  public int getColumnHeadersCount() {
    return columnHeaders_.size();
  }
  /**
   * <code>repeated .ferriswheel.v1.Header column_headers = 6;</code>
   */
  public com.ctrip.ferriswheel.proto.v1.Header getColumnHeaders(int index) {
    return columnHeaders_.get(index);
  }
  /**
   * <code>repeated .ferriswheel.v1.Header column_headers = 6;</code>
   */
  public com.ctrip.ferriswheel.proto.v1.HeaderOrBuilder getColumnHeadersOrBuilder(
      int index) {
    return columnHeaders_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    for (int i = 0; i < rows_.size(); i++) {
      output.writeMessage(2, rows_.get(i));
    }
    if (automaton_ != null) {
      output.writeMessage(3, getAutomaton());
    }
    if (layout_ != null) {
      output.writeMessage(4, getLayout());
    }
    for (int i = 0; i < rowHeaders_.size(); i++) {
      output.writeMessage(5, rowHeaders_.get(i));
    }
    for (int i = 0; i < columnHeaders_.size(); i++) {
      output.writeMessage(6, columnHeaders_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    for (int i = 0; i < rows_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, rows_.get(i));
    }
    if (automaton_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getAutomaton());
    }
    if (layout_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getLayout());
    }
    for (int i = 0; i < rowHeaders_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, rowHeaders_.get(i));
    }
    for (int i = 0; i < columnHeaders_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, columnHeaders_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ctrip.ferriswheel.proto.v1.Table)) {
      return super.equals(obj);
    }
    com.ctrip.ferriswheel.proto.v1.Table other = (com.ctrip.ferriswheel.proto.v1.Table) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (!getRowsList()
        .equals(other.getRowsList())) return false;
    if (hasAutomaton() != other.hasAutomaton()) return false;
    if (hasAutomaton()) {
      if (!getAutomaton()
          .equals(other.getAutomaton())) return false;
    }
    if (hasLayout() != other.hasLayout()) return false;
    if (hasLayout()) {
      if (!getLayout()
          .equals(other.getLayout())) return false;
    }
    if (!getRowHeadersList()
        .equals(other.getRowHeadersList())) return false;
    if (!getColumnHeadersList()
        .equals(other.getColumnHeadersList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    if (getRowsCount() > 0) {
      hash = (37 * hash) + ROWS_FIELD_NUMBER;
      hash = (53 * hash) + getRowsList().hashCode();
    }
    if (hasAutomaton()) {
      hash = (37 * hash) + AUTOMATON_FIELD_NUMBER;
      hash = (53 * hash) + getAutomaton().hashCode();
    }
    if (hasLayout()) {
      hash = (37 * hash) + LAYOUT_FIELD_NUMBER;
      hash = (53 * hash) + getLayout().hashCode();
    }
    if (getRowHeadersCount() > 0) {
      hash = (37 * hash) + ROW_HEADERS_FIELD_NUMBER;
      hash = (53 * hash) + getRowHeadersList().hashCode();
    }
    if (getColumnHeadersCount() > 0) {
      hash = (37 * hash) + COLUMN_HEADERS_FIELD_NUMBER;
      hash = (53 * hash) + getColumnHeadersList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ctrip.ferriswheel.proto.v1.Table parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ctrip.ferriswheel.proto.v1.Table parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ctrip.ferriswheel.proto.v1.Table parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ctrip.ferriswheel.proto.v1.Table parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ctrip.ferriswheel.proto.v1.Table parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ctrip.ferriswheel.proto.v1.Table parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ctrip.ferriswheel.proto.v1.Table parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ctrip.ferriswheel.proto.v1.Table parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ctrip.ferriswheel.proto.v1.Table parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ctrip.ferriswheel.proto.v1.Table parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ctrip.ferriswheel.proto.v1.Table parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ctrip.ferriswheel.proto.v1.Table parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ctrip.ferriswheel.proto.v1.Table prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ferriswheel.v1.Table}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ferriswheel.v1.Table)
      com.ctrip.ferriswheel.proto.v1.TableOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ctrip.ferriswheel.proto.v1.WorkbookOuterClass.internal_static_ferriswheel_v1_Table_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ctrip.ferriswheel.proto.v1.WorkbookOuterClass.internal_static_ferriswheel_v1_Table_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ctrip.ferriswheel.proto.v1.Table.class, com.ctrip.ferriswheel.proto.v1.Table.Builder.class);
    }

    // Construct using com.ctrip.ferriswheel.proto.v1.Table.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getRowsFieldBuilder();
        getRowHeadersFieldBuilder();
        getColumnHeadersFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      name_ = "";

      if (rowsBuilder_ == null) {
        rows_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        rowsBuilder_.clear();
      }
      if (automatonBuilder_ == null) {
        automaton_ = null;
      } else {
        automaton_ = null;
        automatonBuilder_ = null;
      }
      if (layoutBuilder_ == null) {
        layout_ = null;
      } else {
        layout_ = null;
        layoutBuilder_ = null;
      }
      if (rowHeadersBuilder_ == null) {
        rowHeaders_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
      } else {
        rowHeadersBuilder_.clear();
      }
      if (columnHeadersBuilder_ == null) {
        columnHeaders_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
      } else {
        columnHeadersBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ctrip.ferriswheel.proto.v1.WorkbookOuterClass.internal_static_ferriswheel_v1_Table_descriptor;
    }

    @java.lang.Override
    public com.ctrip.ferriswheel.proto.v1.Table getDefaultInstanceForType() {
      return com.ctrip.ferriswheel.proto.v1.Table.getDefaultInstance();
    }

    @java.lang.Override
    public com.ctrip.ferriswheel.proto.v1.Table build() {
      com.ctrip.ferriswheel.proto.v1.Table result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ctrip.ferriswheel.proto.v1.Table buildPartial() {
      com.ctrip.ferriswheel.proto.v1.Table result = new com.ctrip.ferriswheel.proto.v1.Table(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.name_ = name_;
      if (rowsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          rows_ = java.util.Collections.unmodifiableList(rows_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.rows_ = rows_;
      } else {
        result.rows_ = rowsBuilder_.build();
      }
      if (automatonBuilder_ == null) {
        result.automaton_ = automaton_;
      } else {
        result.automaton_ = automatonBuilder_.build();
      }
      if (layoutBuilder_ == null) {
        result.layout_ = layout_;
      } else {
        result.layout_ = layoutBuilder_.build();
      }
      if (rowHeadersBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0)) {
          rowHeaders_ = java.util.Collections.unmodifiableList(rowHeaders_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.rowHeaders_ = rowHeaders_;
      } else {
        result.rowHeaders_ = rowHeadersBuilder_.build();
      }
      if (columnHeadersBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0)) {
          columnHeaders_ = java.util.Collections.unmodifiableList(columnHeaders_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.columnHeaders_ = columnHeaders_;
      } else {
        result.columnHeaders_ = columnHeadersBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ctrip.ferriswheel.proto.v1.Table) {
        return mergeFrom((com.ctrip.ferriswheel.proto.v1.Table)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ctrip.ferriswheel.proto.v1.Table other) {
      if (other == com.ctrip.ferriswheel.proto.v1.Table.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (rowsBuilder_ == null) {
        if (!other.rows_.isEmpty()) {
          if (rows_.isEmpty()) {
            rows_ = other.rows_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureRowsIsMutable();
            rows_.addAll(other.rows_);
          }
          onChanged();
        }
      } else {
        if (!other.rows_.isEmpty()) {
          if (rowsBuilder_.isEmpty()) {
            rowsBuilder_.dispose();
            rowsBuilder_ = null;
            rows_ = other.rows_;
            bitField0_ = (bitField0_ & ~0x00000002);
            rowsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRowsFieldBuilder() : null;
          } else {
            rowsBuilder_.addAllMessages(other.rows_);
          }
        }
      }
      if (other.hasAutomaton()) {
        mergeAutomaton(other.getAutomaton());
      }
      if (other.hasLayout()) {
        mergeLayout(other.getLayout());
      }
      if (rowHeadersBuilder_ == null) {
        if (!other.rowHeaders_.isEmpty()) {
          if (rowHeaders_.isEmpty()) {
            rowHeaders_ = other.rowHeaders_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureRowHeadersIsMutable();
            rowHeaders_.addAll(other.rowHeaders_);
          }
          onChanged();
        }
      } else {
        if (!other.rowHeaders_.isEmpty()) {
          if (rowHeadersBuilder_.isEmpty()) {
            rowHeadersBuilder_.dispose();
            rowHeadersBuilder_ = null;
            rowHeaders_ = other.rowHeaders_;
            bitField0_ = (bitField0_ & ~0x00000010);
            rowHeadersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRowHeadersFieldBuilder() : null;
          } else {
            rowHeadersBuilder_.addAllMessages(other.rowHeaders_);
          }
        }
      }
      if (columnHeadersBuilder_ == null) {
        if (!other.columnHeaders_.isEmpty()) {
          if (columnHeaders_.isEmpty()) {
            columnHeaders_ = other.columnHeaders_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureColumnHeadersIsMutable();
            columnHeaders_.addAll(other.columnHeaders_);
          }
          onChanged();
        }
      } else {
        if (!other.columnHeaders_.isEmpty()) {
          if (columnHeadersBuilder_.isEmpty()) {
            columnHeadersBuilder_.dispose();
            columnHeadersBuilder_ = null;
            columnHeaders_ = other.columnHeaders_;
            bitField0_ = (bitField0_ & ~0x00000020);
            columnHeadersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getColumnHeadersFieldBuilder() : null;
          } else {
            columnHeadersBuilder_.addAllMessages(other.columnHeaders_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ctrip.ferriswheel.proto.v1.Table parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ctrip.ferriswheel.proto.v1.Table) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.ctrip.ferriswheel.proto.v1.Row> rows_ =
      java.util.Collections.emptyList();
    private void ensureRowsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        rows_ = new java.util.ArrayList<com.ctrip.ferriswheel.proto.v1.Row>(rows_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ctrip.ferriswheel.proto.v1.Row, com.ctrip.ferriswheel.proto.v1.Row.Builder, com.ctrip.ferriswheel.proto.v1.RowOrBuilder> rowsBuilder_;

    /**
     * <code>repeated .ferriswheel.v1.Row rows = 2;</code>
     */
    public java.util.List<com.ctrip.ferriswheel.proto.v1.Row> getRowsList() {
      if (rowsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(rows_);
      } else {
        return rowsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .ferriswheel.v1.Row rows = 2;</code>
     */
    public int getRowsCount() {
      if (rowsBuilder_ == null) {
        return rows_.size();
      } else {
        return rowsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .ferriswheel.v1.Row rows = 2;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.Row getRows(int index) {
      if (rowsBuilder_ == null) {
        return rows_.get(index);
      } else {
        return rowsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .ferriswheel.v1.Row rows = 2;</code>
     */
    public Builder setRows(
        int index, com.ctrip.ferriswheel.proto.v1.Row value) {
      if (rowsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRowsIsMutable();
        rows_.set(index, value);
        onChanged();
      } else {
        rowsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ferriswheel.v1.Row rows = 2;</code>
     */
    public Builder setRows(
        int index, com.ctrip.ferriswheel.proto.v1.Row.Builder builderForValue) {
      if (rowsBuilder_ == null) {
        ensureRowsIsMutable();
        rows_.set(index, builderForValue.build());
        onChanged();
      } else {
        rowsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ferriswheel.v1.Row rows = 2;</code>
     */
    public Builder addRows(com.ctrip.ferriswheel.proto.v1.Row value) {
      if (rowsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRowsIsMutable();
        rows_.add(value);
        onChanged();
      } else {
        rowsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .ferriswheel.v1.Row rows = 2;</code>
     */
    public Builder addRows(
        int index, com.ctrip.ferriswheel.proto.v1.Row value) {
      if (rowsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRowsIsMutable();
        rows_.add(index, value);
        onChanged();
      } else {
        rowsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ferriswheel.v1.Row rows = 2;</code>
     */
    public Builder addRows(
        com.ctrip.ferriswheel.proto.v1.Row.Builder builderForValue) {
      if (rowsBuilder_ == null) {
        ensureRowsIsMutable();
        rows_.add(builderForValue.build());
        onChanged();
      } else {
        rowsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ferriswheel.v1.Row rows = 2;</code>
     */
    public Builder addRows(
        int index, com.ctrip.ferriswheel.proto.v1.Row.Builder builderForValue) {
      if (rowsBuilder_ == null) {
        ensureRowsIsMutable();
        rows_.add(index, builderForValue.build());
        onChanged();
      } else {
        rowsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ferriswheel.v1.Row rows = 2;</code>
     */
    public Builder addAllRows(
        java.lang.Iterable<? extends com.ctrip.ferriswheel.proto.v1.Row> values) {
      if (rowsBuilder_ == null) {
        ensureRowsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, rows_);
        onChanged();
      } else {
        rowsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .ferriswheel.v1.Row rows = 2;</code>
     */
    public Builder clearRows() {
      if (rowsBuilder_ == null) {
        rows_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        rowsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .ferriswheel.v1.Row rows = 2;</code>
     */
    public Builder removeRows(int index) {
      if (rowsBuilder_ == null) {
        ensureRowsIsMutable();
        rows_.remove(index);
        onChanged();
      } else {
        rowsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .ferriswheel.v1.Row rows = 2;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.Row.Builder getRowsBuilder(
        int index) {
      return getRowsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .ferriswheel.v1.Row rows = 2;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.RowOrBuilder getRowsOrBuilder(
        int index) {
      if (rowsBuilder_ == null) {
        return rows_.get(index);  } else {
        return rowsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .ferriswheel.v1.Row rows = 2;</code>
     */
    public java.util.List<? extends com.ctrip.ferriswheel.proto.v1.RowOrBuilder> 
         getRowsOrBuilderList() {
      if (rowsBuilder_ != null) {
        return rowsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(rows_);
      }
    }
    /**
     * <code>repeated .ferriswheel.v1.Row rows = 2;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.Row.Builder addRowsBuilder() {
      return getRowsFieldBuilder().addBuilder(
          com.ctrip.ferriswheel.proto.v1.Row.getDefaultInstance());
    }
    /**
     * <code>repeated .ferriswheel.v1.Row rows = 2;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.Row.Builder addRowsBuilder(
        int index) {
      return getRowsFieldBuilder().addBuilder(
          index, com.ctrip.ferriswheel.proto.v1.Row.getDefaultInstance());
    }
    /**
     * <code>repeated .ferriswheel.v1.Row rows = 2;</code>
     */
    public java.util.List<com.ctrip.ferriswheel.proto.v1.Row.Builder> 
         getRowsBuilderList() {
      return getRowsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ctrip.ferriswheel.proto.v1.Row, com.ctrip.ferriswheel.proto.v1.Row.Builder, com.ctrip.ferriswheel.proto.v1.RowOrBuilder> 
        getRowsFieldBuilder() {
      if (rowsBuilder_ == null) {
        rowsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.ctrip.ferriswheel.proto.v1.Row, com.ctrip.ferriswheel.proto.v1.Row.Builder, com.ctrip.ferriswheel.proto.v1.RowOrBuilder>(
                rows_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        rows_ = null;
      }
      return rowsBuilder_;
    }

    private com.ctrip.ferriswheel.proto.v1.TableAutomaton automaton_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ctrip.ferriswheel.proto.v1.TableAutomaton, com.ctrip.ferriswheel.proto.v1.TableAutomaton.Builder, com.ctrip.ferriswheel.proto.v1.TableAutomatonOrBuilder> automatonBuilder_;
    /**
     * <code>.ferriswheel.v1.TableAutomaton automaton = 3;</code>
     */
    public boolean hasAutomaton() {
      return automatonBuilder_ != null || automaton_ != null;
    }
    /**
     * <code>.ferriswheel.v1.TableAutomaton automaton = 3;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.TableAutomaton getAutomaton() {
      if (automatonBuilder_ == null) {
        return automaton_ == null ? com.ctrip.ferriswheel.proto.v1.TableAutomaton.getDefaultInstance() : automaton_;
      } else {
        return automatonBuilder_.getMessage();
      }
    }
    /**
     * <code>.ferriswheel.v1.TableAutomaton automaton = 3;</code>
     */
    public Builder setAutomaton(com.ctrip.ferriswheel.proto.v1.TableAutomaton value) {
      if (automatonBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        automaton_ = value;
        onChanged();
      } else {
        automatonBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.ferriswheel.v1.TableAutomaton automaton = 3;</code>
     */
    public Builder setAutomaton(
        com.ctrip.ferriswheel.proto.v1.TableAutomaton.Builder builderForValue) {
      if (automatonBuilder_ == null) {
        automaton_ = builderForValue.build();
        onChanged();
      } else {
        automatonBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.ferriswheel.v1.TableAutomaton automaton = 3;</code>
     */
    public Builder mergeAutomaton(com.ctrip.ferriswheel.proto.v1.TableAutomaton value) {
      if (automatonBuilder_ == null) {
        if (automaton_ != null) {
          automaton_ =
            com.ctrip.ferriswheel.proto.v1.TableAutomaton.newBuilder(automaton_).mergeFrom(value).buildPartial();
        } else {
          automaton_ = value;
        }
        onChanged();
      } else {
        automatonBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.ferriswheel.v1.TableAutomaton automaton = 3;</code>
     */
    public Builder clearAutomaton() {
      if (automatonBuilder_ == null) {
        automaton_ = null;
        onChanged();
      } else {
        automaton_ = null;
        automatonBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.ferriswheel.v1.TableAutomaton automaton = 3;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.TableAutomaton.Builder getAutomatonBuilder() {
      
      onChanged();
      return getAutomatonFieldBuilder().getBuilder();
    }
    /**
     * <code>.ferriswheel.v1.TableAutomaton automaton = 3;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.TableAutomatonOrBuilder getAutomatonOrBuilder() {
      if (automatonBuilder_ != null) {
        return automatonBuilder_.getMessageOrBuilder();
      } else {
        return automaton_ == null ?
            com.ctrip.ferriswheel.proto.v1.TableAutomaton.getDefaultInstance() : automaton_;
      }
    }
    /**
     * <code>.ferriswheel.v1.TableAutomaton automaton = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ctrip.ferriswheel.proto.v1.TableAutomaton, com.ctrip.ferriswheel.proto.v1.TableAutomaton.Builder, com.ctrip.ferriswheel.proto.v1.TableAutomatonOrBuilder> 
        getAutomatonFieldBuilder() {
      if (automatonBuilder_ == null) {
        automatonBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ctrip.ferriswheel.proto.v1.TableAutomaton, com.ctrip.ferriswheel.proto.v1.TableAutomaton.Builder, com.ctrip.ferriswheel.proto.v1.TableAutomatonOrBuilder>(
                getAutomaton(),
                getParentForChildren(),
                isClean());
        automaton_ = null;
      }
      return automatonBuilder_;
    }

    private com.ctrip.ferriswheel.proto.v1.Layout layout_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ctrip.ferriswheel.proto.v1.Layout, com.ctrip.ferriswheel.proto.v1.Layout.Builder, com.ctrip.ferriswheel.proto.v1.LayoutOrBuilder> layoutBuilder_;
    /**
     * <code>.ferriswheel.v1.Layout layout = 4;</code>
     */
    public boolean hasLayout() {
      return layoutBuilder_ != null || layout_ != null;
    }
    /**
     * <code>.ferriswheel.v1.Layout layout = 4;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.Layout getLayout() {
      if (layoutBuilder_ == null) {
        return layout_ == null ? com.ctrip.ferriswheel.proto.v1.Layout.getDefaultInstance() : layout_;
      } else {
        return layoutBuilder_.getMessage();
      }
    }
    /**
     * <code>.ferriswheel.v1.Layout layout = 4;</code>
     */
    public Builder setLayout(com.ctrip.ferriswheel.proto.v1.Layout value) {
      if (layoutBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        layout_ = value;
        onChanged();
      } else {
        layoutBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.ferriswheel.v1.Layout layout = 4;</code>
     */
    public Builder setLayout(
        com.ctrip.ferriswheel.proto.v1.Layout.Builder builderForValue) {
      if (layoutBuilder_ == null) {
        layout_ = builderForValue.build();
        onChanged();
      } else {
        layoutBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.ferriswheel.v1.Layout layout = 4;</code>
     */
    public Builder mergeLayout(com.ctrip.ferriswheel.proto.v1.Layout value) {
      if (layoutBuilder_ == null) {
        if (layout_ != null) {
          layout_ =
            com.ctrip.ferriswheel.proto.v1.Layout.newBuilder(layout_).mergeFrom(value).buildPartial();
        } else {
          layout_ = value;
        }
        onChanged();
      } else {
        layoutBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.ferriswheel.v1.Layout layout = 4;</code>
     */
    public Builder clearLayout() {
      if (layoutBuilder_ == null) {
        layout_ = null;
        onChanged();
      } else {
        layout_ = null;
        layoutBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.ferriswheel.v1.Layout layout = 4;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.Layout.Builder getLayoutBuilder() {
      
      onChanged();
      return getLayoutFieldBuilder().getBuilder();
    }
    /**
     * <code>.ferriswheel.v1.Layout layout = 4;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.LayoutOrBuilder getLayoutOrBuilder() {
      if (layoutBuilder_ != null) {
        return layoutBuilder_.getMessageOrBuilder();
      } else {
        return layout_ == null ?
            com.ctrip.ferriswheel.proto.v1.Layout.getDefaultInstance() : layout_;
      }
    }
    /**
     * <code>.ferriswheel.v1.Layout layout = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ctrip.ferriswheel.proto.v1.Layout, com.ctrip.ferriswheel.proto.v1.Layout.Builder, com.ctrip.ferriswheel.proto.v1.LayoutOrBuilder> 
        getLayoutFieldBuilder() {
      if (layoutBuilder_ == null) {
        layoutBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ctrip.ferriswheel.proto.v1.Layout, com.ctrip.ferriswheel.proto.v1.Layout.Builder, com.ctrip.ferriswheel.proto.v1.LayoutOrBuilder>(
                getLayout(),
                getParentForChildren(),
                isClean());
        layout_ = null;
      }
      return layoutBuilder_;
    }

    private java.util.List<com.ctrip.ferriswheel.proto.v1.Header> rowHeaders_ =
      java.util.Collections.emptyList();
    private void ensureRowHeadersIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        rowHeaders_ = new java.util.ArrayList<com.ctrip.ferriswheel.proto.v1.Header>(rowHeaders_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ctrip.ferriswheel.proto.v1.Header, com.ctrip.ferriswheel.proto.v1.Header.Builder, com.ctrip.ferriswheel.proto.v1.HeaderOrBuilder> rowHeadersBuilder_;

    /**
     * <code>repeated .ferriswheel.v1.Header row_headers = 5;</code>
     */
    public java.util.List<com.ctrip.ferriswheel.proto.v1.Header> getRowHeadersList() {
      if (rowHeadersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(rowHeaders_);
      } else {
        return rowHeadersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .ferriswheel.v1.Header row_headers = 5;</code>
     */
    public int getRowHeadersCount() {
      if (rowHeadersBuilder_ == null) {
        return rowHeaders_.size();
      } else {
        return rowHeadersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .ferriswheel.v1.Header row_headers = 5;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.Header getRowHeaders(int index) {
      if (rowHeadersBuilder_ == null) {
        return rowHeaders_.get(index);
      } else {
        return rowHeadersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .ferriswheel.v1.Header row_headers = 5;</code>
     */
    public Builder setRowHeaders(
        int index, com.ctrip.ferriswheel.proto.v1.Header value) {
      if (rowHeadersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRowHeadersIsMutable();
        rowHeaders_.set(index, value);
        onChanged();
      } else {
        rowHeadersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ferriswheel.v1.Header row_headers = 5;</code>
     */
    public Builder setRowHeaders(
        int index, com.ctrip.ferriswheel.proto.v1.Header.Builder builderForValue) {
      if (rowHeadersBuilder_ == null) {
        ensureRowHeadersIsMutable();
        rowHeaders_.set(index, builderForValue.build());
        onChanged();
      } else {
        rowHeadersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ferriswheel.v1.Header row_headers = 5;</code>
     */
    public Builder addRowHeaders(com.ctrip.ferriswheel.proto.v1.Header value) {
      if (rowHeadersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRowHeadersIsMutable();
        rowHeaders_.add(value);
        onChanged();
      } else {
        rowHeadersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .ferriswheel.v1.Header row_headers = 5;</code>
     */
    public Builder addRowHeaders(
        int index, com.ctrip.ferriswheel.proto.v1.Header value) {
      if (rowHeadersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRowHeadersIsMutable();
        rowHeaders_.add(index, value);
        onChanged();
      } else {
        rowHeadersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ferriswheel.v1.Header row_headers = 5;</code>
     */
    public Builder addRowHeaders(
        com.ctrip.ferriswheel.proto.v1.Header.Builder builderForValue) {
      if (rowHeadersBuilder_ == null) {
        ensureRowHeadersIsMutable();
        rowHeaders_.add(builderForValue.build());
        onChanged();
      } else {
        rowHeadersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ferriswheel.v1.Header row_headers = 5;</code>
     */
    public Builder addRowHeaders(
        int index, com.ctrip.ferriswheel.proto.v1.Header.Builder builderForValue) {
      if (rowHeadersBuilder_ == null) {
        ensureRowHeadersIsMutable();
        rowHeaders_.add(index, builderForValue.build());
        onChanged();
      } else {
        rowHeadersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ferriswheel.v1.Header row_headers = 5;</code>
     */
    public Builder addAllRowHeaders(
        java.lang.Iterable<? extends com.ctrip.ferriswheel.proto.v1.Header> values) {
      if (rowHeadersBuilder_ == null) {
        ensureRowHeadersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, rowHeaders_);
        onChanged();
      } else {
        rowHeadersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .ferriswheel.v1.Header row_headers = 5;</code>
     */
    public Builder clearRowHeaders() {
      if (rowHeadersBuilder_ == null) {
        rowHeaders_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        rowHeadersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .ferriswheel.v1.Header row_headers = 5;</code>
     */
    public Builder removeRowHeaders(int index) {
      if (rowHeadersBuilder_ == null) {
        ensureRowHeadersIsMutable();
        rowHeaders_.remove(index);
        onChanged();
      } else {
        rowHeadersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .ferriswheel.v1.Header row_headers = 5;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.Header.Builder getRowHeadersBuilder(
        int index) {
      return getRowHeadersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .ferriswheel.v1.Header row_headers = 5;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.HeaderOrBuilder getRowHeadersOrBuilder(
        int index) {
      if (rowHeadersBuilder_ == null) {
        return rowHeaders_.get(index);  } else {
        return rowHeadersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .ferriswheel.v1.Header row_headers = 5;</code>
     */
    public java.util.List<? extends com.ctrip.ferriswheel.proto.v1.HeaderOrBuilder> 
         getRowHeadersOrBuilderList() {
      if (rowHeadersBuilder_ != null) {
        return rowHeadersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(rowHeaders_);
      }
    }
    /**
     * <code>repeated .ferriswheel.v1.Header row_headers = 5;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.Header.Builder addRowHeadersBuilder() {
      return getRowHeadersFieldBuilder().addBuilder(
          com.ctrip.ferriswheel.proto.v1.Header.getDefaultInstance());
    }
    /**
     * <code>repeated .ferriswheel.v1.Header row_headers = 5;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.Header.Builder addRowHeadersBuilder(
        int index) {
      return getRowHeadersFieldBuilder().addBuilder(
          index, com.ctrip.ferriswheel.proto.v1.Header.getDefaultInstance());
    }
    /**
     * <code>repeated .ferriswheel.v1.Header row_headers = 5;</code>
     */
    public java.util.List<com.ctrip.ferriswheel.proto.v1.Header.Builder> 
         getRowHeadersBuilderList() {
      return getRowHeadersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ctrip.ferriswheel.proto.v1.Header, com.ctrip.ferriswheel.proto.v1.Header.Builder, com.ctrip.ferriswheel.proto.v1.HeaderOrBuilder> 
        getRowHeadersFieldBuilder() {
      if (rowHeadersBuilder_ == null) {
        rowHeadersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.ctrip.ferriswheel.proto.v1.Header, com.ctrip.ferriswheel.proto.v1.Header.Builder, com.ctrip.ferriswheel.proto.v1.HeaderOrBuilder>(
                rowHeaders_,
                ((bitField0_ & 0x00000010) != 0),
                getParentForChildren(),
                isClean());
        rowHeaders_ = null;
      }
      return rowHeadersBuilder_;
    }

    private java.util.List<com.ctrip.ferriswheel.proto.v1.Header> columnHeaders_ =
      java.util.Collections.emptyList();
    private void ensureColumnHeadersIsMutable() {
      if (!((bitField0_ & 0x00000020) != 0)) {
        columnHeaders_ = new java.util.ArrayList<com.ctrip.ferriswheel.proto.v1.Header>(columnHeaders_);
        bitField0_ |= 0x00000020;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ctrip.ferriswheel.proto.v1.Header, com.ctrip.ferriswheel.proto.v1.Header.Builder, com.ctrip.ferriswheel.proto.v1.HeaderOrBuilder> columnHeadersBuilder_;

    /**
     * <code>repeated .ferriswheel.v1.Header column_headers = 6;</code>
     */
    public java.util.List<com.ctrip.ferriswheel.proto.v1.Header> getColumnHeadersList() {
      if (columnHeadersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(columnHeaders_);
      } else {
        return columnHeadersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .ferriswheel.v1.Header column_headers = 6;</code>
     */
    public int getColumnHeadersCount() {
      if (columnHeadersBuilder_ == null) {
        return columnHeaders_.size();
      } else {
        return columnHeadersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .ferriswheel.v1.Header column_headers = 6;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.Header getColumnHeaders(int index) {
      if (columnHeadersBuilder_ == null) {
        return columnHeaders_.get(index);
      } else {
        return columnHeadersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .ferriswheel.v1.Header column_headers = 6;</code>
     */
    public Builder setColumnHeaders(
        int index, com.ctrip.ferriswheel.proto.v1.Header value) {
      if (columnHeadersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureColumnHeadersIsMutable();
        columnHeaders_.set(index, value);
        onChanged();
      } else {
        columnHeadersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ferriswheel.v1.Header column_headers = 6;</code>
     */
    public Builder setColumnHeaders(
        int index, com.ctrip.ferriswheel.proto.v1.Header.Builder builderForValue) {
      if (columnHeadersBuilder_ == null) {
        ensureColumnHeadersIsMutable();
        columnHeaders_.set(index, builderForValue.build());
        onChanged();
      } else {
        columnHeadersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ferriswheel.v1.Header column_headers = 6;</code>
     */
    public Builder addColumnHeaders(com.ctrip.ferriswheel.proto.v1.Header value) {
      if (columnHeadersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureColumnHeadersIsMutable();
        columnHeaders_.add(value);
        onChanged();
      } else {
        columnHeadersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .ferriswheel.v1.Header column_headers = 6;</code>
     */
    public Builder addColumnHeaders(
        int index, com.ctrip.ferriswheel.proto.v1.Header value) {
      if (columnHeadersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureColumnHeadersIsMutable();
        columnHeaders_.add(index, value);
        onChanged();
      } else {
        columnHeadersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ferriswheel.v1.Header column_headers = 6;</code>
     */
    public Builder addColumnHeaders(
        com.ctrip.ferriswheel.proto.v1.Header.Builder builderForValue) {
      if (columnHeadersBuilder_ == null) {
        ensureColumnHeadersIsMutable();
        columnHeaders_.add(builderForValue.build());
        onChanged();
      } else {
        columnHeadersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ferriswheel.v1.Header column_headers = 6;</code>
     */
    public Builder addColumnHeaders(
        int index, com.ctrip.ferriswheel.proto.v1.Header.Builder builderForValue) {
      if (columnHeadersBuilder_ == null) {
        ensureColumnHeadersIsMutable();
        columnHeaders_.add(index, builderForValue.build());
        onChanged();
      } else {
        columnHeadersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ferriswheel.v1.Header column_headers = 6;</code>
     */
    public Builder addAllColumnHeaders(
        java.lang.Iterable<? extends com.ctrip.ferriswheel.proto.v1.Header> values) {
      if (columnHeadersBuilder_ == null) {
        ensureColumnHeadersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, columnHeaders_);
        onChanged();
      } else {
        columnHeadersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .ferriswheel.v1.Header column_headers = 6;</code>
     */
    public Builder clearColumnHeaders() {
      if (columnHeadersBuilder_ == null) {
        columnHeaders_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
      } else {
        columnHeadersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .ferriswheel.v1.Header column_headers = 6;</code>
     */
    public Builder removeColumnHeaders(int index) {
      if (columnHeadersBuilder_ == null) {
        ensureColumnHeadersIsMutable();
        columnHeaders_.remove(index);
        onChanged();
      } else {
        columnHeadersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .ferriswheel.v1.Header column_headers = 6;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.Header.Builder getColumnHeadersBuilder(
        int index) {
      return getColumnHeadersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .ferriswheel.v1.Header column_headers = 6;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.HeaderOrBuilder getColumnHeadersOrBuilder(
        int index) {
      if (columnHeadersBuilder_ == null) {
        return columnHeaders_.get(index);  } else {
        return columnHeadersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .ferriswheel.v1.Header column_headers = 6;</code>
     */
    public java.util.List<? extends com.ctrip.ferriswheel.proto.v1.HeaderOrBuilder> 
         getColumnHeadersOrBuilderList() {
      if (columnHeadersBuilder_ != null) {
        return columnHeadersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(columnHeaders_);
      }
    }
    /**
     * <code>repeated .ferriswheel.v1.Header column_headers = 6;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.Header.Builder addColumnHeadersBuilder() {
      return getColumnHeadersFieldBuilder().addBuilder(
          com.ctrip.ferriswheel.proto.v1.Header.getDefaultInstance());
    }
    /**
     * <code>repeated .ferriswheel.v1.Header column_headers = 6;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.Header.Builder addColumnHeadersBuilder(
        int index) {
      return getColumnHeadersFieldBuilder().addBuilder(
          index, com.ctrip.ferriswheel.proto.v1.Header.getDefaultInstance());
    }
    /**
     * <code>repeated .ferriswheel.v1.Header column_headers = 6;</code>
     */
    public java.util.List<com.ctrip.ferriswheel.proto.v1.Header.Builder> 
         getColumnHeadersBuilderList() {
      return getColumnHeadersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ctrip.ferriswheel.proto.v1.Header, com.ctrip.ferriswheel.proto.v1.Header.Builder, com.ctrip.ferriswheel.proto.v1.HeaderOrBuilder> 
        getColumnHeadersFieldBuilder() {
      if (columnHeadersBuilder_ == null) {
        columnHeadersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.ctrip.ferriswheel.proto.v1.Header, com.ctrip.ferriswheel.proto.v1.Header.Builder, com.ctrip.ferriswheel.proto.v1.HeaderOrBuilder>(
                columnHeaders_,
                ((bitField0_ & 0x00000020) != 0),
                getParentForChildren(),
                isClean());
        columnHeaders_ = null;
      }
      return columnHeadersBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ferriswheel.v1.Table)
  }

  // @@protoc_insertion_point(class_scope:ferriswheel.v1.Table)
  private static final com.ctrip.ferriswheel.proto.v1.Table DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ctrip.ferriswheel.proto.v1.Table();
  }

  public static com.ctrip.ferriswheel.proto.v1.Table getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Table>
      PARSER = new com.google.protobuf.AbstractParser<Table>() {
    @java.lang.Override
    public Table parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Table(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Table> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Table> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ctrip.ferriswheel.proto.v1.Table getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

