// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/ctrip/ferriswheel/proto/workbook.proto

package com.ctrip.ferriswheel.proto.v1;

/**
 * Protobuf type {@code ferriswheel.v1.UnionValue}
 */
public  final class UnionValue extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ferriswheel.v1.UnionValue)
    UnionValueOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UnionValue.newBuilder() to construct.
  private UnionValue(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UnionValue() {
    formulaString_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UnionValue(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            formulaString_ = s;
            break;
          }
          case 16: {
            int rawValue = input.readEnum();
            valueCase_ = 2;
            value_ = rawValue;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            valueCase_ = 3;
            value_ = s;
            break;
          }
          case 32: {
            valueCase_ = 4;
            value_ = input.readBool();
            break;
          }
          case 42: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (valueCase_ == 5) {
              subBuilder = ((com.google.protobuf.Timestamp) value_).toBuilder();
            }
            value_ =
                input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.google.protobuf.Timestamp) value_);
              value_ = subBuilder.buildPartial();
            }
            valueCase_ = 5;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();
            valueCase_ = 6;
            value_ = s;
            break;
          }
          case 58: {
            com.ctrip.ferriswheel.proto.v1.ListValue.Builder subBuilder = null;
            if (valueCase_ == 7) {
              subBuilder = ((com.ctrip.ferriswheel.proto.v1.ListValue) value_).toBuilder();
            }
            value_ =
                input.readMessage(com.ctrip.ferriswheel.proto.v1.ListValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.ctrip.ferriswheel.proto.v1.ListValue) value_);
              value_ = subBuilder.buildPartial();
            }
            valueCase_ = 7;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ctrip.ferriswheel.proto.v1.WorkbookOuterClass.internal_static_ferriswheel_v1_UnionValue_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ctrip.ferriswheel.proto.v1.WorkbookOuterClass.internal_static_ferriswheel_v1_UnionValue_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ctrip.ferriswheel.proto.v1.UnionValue.class, com.ctrip.ferriswheel.proto.v1.UnionValue.Builder.class);
  }

  private int valueCase_ = 0;
  private java.lang.Object value_;
  public enum ValueCase
      implements com.google.protobuf.Internal.EnumLite {
    ERROR(2),
    DECIMAL(3),
    BOOLEAN(4),
    DATE(5),
    STRING(6),
    LIST(7),
    VALUE_NOT_SET(0);
    private final int value;
    private ValueCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ValueCase valueOf(int value) {
      return forNumber(value);
    }

    public static ValueCase forNumber(int value) {
      switch (value) {
        case 2: return ERROR;
        case 3: return DECIMAL;
        case 4: return BOOLEAN;
        case 5: return DATE;
        case 6: return STRING;
        case 7: return LIST;
        case 0: return VALUE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ValueCase
  getValueCase() {
    return ValueCase.forNumber(
        valueCase_);
  }

  public static final int FORMULA_STRING_FIELD_NUMBER = 1;
  private volatile java.lang.Object formulaString_;
  /**
   * <code>string formula_string = 1;</code>
   */
  public java.lang.String getFormulaString() {
    java.lang.Object ref = formulaString_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      formulaString_ = s;
      return s;
    }
  }
  /**
   * <code>string formula_string = 1;</code>
   */
  public com.google.protobuf.ByteString
      getFormulaStringBytes() {
    java.lang.Object ref = formulaString_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      formulaString_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ERROR_FIELD_NUMBER = 2;
  /**
   * <code>.ferriswheel.v1.ErrorCode error = 2;</code>
   */
  public int getErrorValue() {
    if (valueCase_ == 2) {
      return (java.lang.Integer) value_;
    }
    return 0;
  }
  /**
   * <code>.ferriswheel.v1.ErrorCode error = 2;</code>
   */
  public com.ctrip.ferriswheel.proto.v1.ErrorCode getError() {
    if (valueCase_ == 2) {
      @SuppressWarnings("deprecation")
      com.ctrip.ferriswheel.proto.v1.ErrorCode result = com.ctrip.ferriswheel.proto.v1.ErrorCode.valueOf(
          (java.lang.Integer) value_);
      return result == null ? com.ctrip.ferriswheel.proto.v1.ErrorCode.UNRECOGNIZED : result;
    }
    return com.ctrip.ferriswheel.proto.v1.ErrorCode.EC_UNSET;
  }

  public static final int DECIMAL_FIELD_NUMBER = 3;
  /**
   * <code>string decimal = 3;</code>
   */
  public java.lang.String getDecimal() {
    java.lang.Object ref = "";
    if (valueCase_ == 3) {
      ref = value_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (valueCase_ == 3) {
        value_ = s;
      }
      return s;
    }
  }
  /**
   * <code>string decimal = 3;</code>
   */
  public com.google.protobuf.ByteString
      getDecimalBytes() {
    java.lang.Object ref = "";
    if (valueCase_ == 3) {
      ref = value_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (valueCase_ == 3) {
        value_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BOOLEAN_FIELD_NUMBER = 4;
  /**
   * <code>bool boolean = 4;</code>
   */
  public boolean getBoolean() {
    if (valueCase_ == 4) {
      return (java.lang.Boolean) value_;
    }
    return false;
  }

  public static final int DATE_FIELD_NUMBER = 5;
  /**
   * <code>.google.protobuf.Timestamp date = 5;</code>
   */
  public boolean hasDate() {
    return valueCase_ == 5;
  }
  /**
   * <code>.google.protobuf.Timestamp date = 5;</code>
   */
  public com.google.protobuf.Timestamp getDate() {
    if (valueCase_ == 5) {
       return (com.google.protobuf.Timestamp) value_;
    }
    return com.google.protobuf.Timestamp.getDefaultInstance();
  }
  /**
   * <code>.google.protobuf.Timestamp date = 5;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getDateOrBuilder() {
    if (valueCase_ == 5) {
       return (com.google.protobuf.Timestamp) value_;
    }
    return com.google.protobuf.Timestamp.getDefaultInstance();
  }

  public static final int STRING_FIELD_NUMBER = 6;
  /**
   * <code>string string = 6;</code>
   */
  public java.lang.String getString() {
    java.lang.Object ref = "";
    if (valueCase_ == 6) {
      ref = value_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (valueCase_ == 6) {
        value_ = s;
      }
      return s;
    }
  }
  /**
   * <code>string string = 6;</code>
   */
  public com.google.protobuf.ByteString
      getStringBytes() {
    java.lang.Object ref = "";
    if (valueCase_ == 6) {
      ref = value_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (valueCase_ == 6) {
        value_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LIST_FIELD_NUMBER = 7;
  /**
   * <code>.ferriswheel.v1.ListValue list = 7;</code>
   */
  public boolean hasList() {
    return valueCase_ == 7;
  }
  /**
   * <code>.ferriswheel.v1.ListValue list = 7;</code>
   */
  public com.ctrip.ferriswheel.proto.v1.ListValue getList() {
    if (valueCase_ == 7) {
       return (com.ctrip.ferriswheel.proto.v1.ListValue) value_;
    }
    return com.ctrip.ferriswheel.proto.v1.ListValue.getDefaultInstance();
  }
  /**
   * <code>.ferriswheel.v1.ListValue list = 7;</code>
   */
  public com.ctrip.ferriswheel.proto.v1.ListValueOrBuilder getListOrBuilder() {
    if (valueCase_ == 7) {
       return (com.ctrip.ferriswheel.proto.v1.ListValue) value_;
    }
    return com.ctrip.ferriswheel.proto.v1.ListValue.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getFormulaStringBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, formulaString_);
    }
    if (valueCase_ == 2) {
      output.writeEnum(2, ((java.lang.Integer) value_));
    }
    if (valueCase_ == 3) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, value_);
    }
    if (valueCase_ == 4) {
      output.writeBool(
          4, (boolean)((java.lang.Boolean) value_));
    }
    if (valueCase_ == 5) {
      output.writeMessage(5, (com.google.protobuf.Timestamp) value_);
    }
    if (valueCase_ == 6) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, value_);
    }
    if (valueCase_ == 7) {
      output.writeMessage(7, (com.ctrip.ferriswheel.proto.v1.ListValue) value_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getFormulaStringBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, formulaString_);
    }
    if (valueCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, ((java.lang.Integer) value_));
    }
    if (valueCase_ == 3) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, value_);
    }
    if (valueCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(
            4, (boolean)((java.lang.Boolean) value_));
    }
    if (valueCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (com.google.protobuf.Timestamp) value_);
    }
    if (valueCase_ == 6) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, value_);
    }
    if (valueCase_ == 7) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, (com.ctrip.ferriswheel.proto.v1.ListValue) value_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ctrip.ferriswheel.proto.v1.UnionValue)) {
      return super.equals(obj);
    }
    com.ctrip.ferriswheel.proto.v1.UnionValue other = (com.ctrip.ferriswheel.proto.v1.UnionValue) obj;

    if (!getFormulaString()
        .equals(other.getFormulaString())) return false;
    if (!getValueCase().equals(other.getValueCase())) return false;
    switch (valueCase_) {
      case 2:
        if (getErrorValue()
            != other.getErrorValue()) return false;
        break;
      case 3:
        if (!getDecimal()
            .equals(other.getDecimal())) return false;
        break;
      case 4:
        if (getBoolean()
            != other.getBoolean()) return false;
        break;
      case 5:
        if (!getDate()
            .equals(other.getDate())) return false;
        break;
      case 6:
        if (!getString()
            .equals(other.getString())) return false;
        break;
      case 7:
        if (!getList()
            .equals(other.getList())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FORMULA_STRING_FIELD_NUMBER;
    hash = (53 * hash) + getFormulaString().hashCode();
    switch (valueCase_) {
      case 2:
        hash = (37 * hash) + ERROR_FIELD_NUMBER;
        hash = (53 * hash) + getErrorValue();
        break;
      case 3:
        hash = (37 * hash) + DECIMAL_FIELD_NUMBER;
        hash = (53 * hash) + getDecimal().hashCode();
        break;
      case 4:
        hash = (37 * hash) + BOOLEAN_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getBoolean());
        break;
      case 5:
        hash = (37 * hash) + DATE_FIELD_NUMBER;
        hash = (53 * hash) + getDate().hashCode();
        break;
      case 6:
        hash = (37 * hash) + STRING_FIELD_NUMBER;
        hash = (53 * hash) + getString().hashCode();
        break;
      case 7:
        hash = (37 * hash) + LIST_FIELD_NUMBER;
        hash = (53 * hash) + getList().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ctrip.ferriswheel.proto.v1.UnionValue parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ctrip.ferriswheel.proto.v1.UnionValue parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ctrip.ferriswheel.proto.v1.UnionValue parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ctrip.ferriswheel.proto.v1.UnionValue parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ctrip.ferriswheel.proto.v1.UnionValue parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ctrip.ferriswheel.proto.v1.UnionValue parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ctrip.ferriswheel.proto.v1.UnionValue parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ctrip.ferriswheel.proto.v1.UnionValue parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ctrip.ferriswheel.proto.v1.UnionValue parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ctrip.ferriswheel.proto.v1.UnionValue parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ctrip.ferriswheel.proto.v1.UnionValue parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ctrip.ferriswheel.proto.v1.UnionValue parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ctrip.ferriswheel.proto.v1.UnionValue prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ferriswheel.v1.UnionValue}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ferriswheel.v1.UnionValue)
      com.ctrip.ferriswheel.proto.v1.UnionValueOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ctrip.ferriswheel.proto.v1.WorkbookOuterClass.internal_static_ferriswheel_v1_UnionValue_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ctrip.ferriswheel.proto.v1.WorkbookOuterClass.internal_static_ferriswheel_v1_UnionValue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ctrip.ferriswheel.proto.v1.UnionValue.class, com.ctrip.ferriswheel.proto.v1.UnionValue.Builder.class);
    }

    // Construct using com.ctrip.ferriswheel.proto.v1.UnionValue.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      formulaString_ = "";

      valueCase_ = 0;
      value_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ctrip.ferriswheel.proto.v1.WorkbookOuterClass.internal_static_ferriswheel_v1_UnionValue_descriptor;
    }

    @java.lang.Override
    public com.ctrip.ferriswheel.proto.v1.UnionValue getDefaultInstanceForType() {
      return com.ctrip.ferriswheel.proto.v1.UnionValue.getDefaultInstance();
    }

    @java.lang.Override
    public com.ctrip.ferriswheel.proto.v1.UnionValue build() {
      com.ctrip.ferriswheel.proto.v1.UnionValue result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ctrip.ferriswheel.proto.v1.UnionValue buildPartial() {
      com.ctrip.ferriswheel.proto.v1.UnionValue result = new com.ctrip.ferriswheel.proto.v1.UnionValue(this);
      result.formulaString_ = formulaString_;
      if (valueCase_ == 2) {
        result.value_ = value_;
      }
      if (valueCase_ == 3) {
        result.value_ = value_;
      }
      if (valueCase_ == 4) {
        result.value_ = value_;
      }
      if (valueCase_ == 5) {
        if (dateBuilder_ == null) {
          result.value_ = value_;
        } else {
          result.value_ = dateBuilder_.build();
        }
      }
      if (valueCase_ == 6) {
        result.value_ = value_;
      }
      if (valueCase_ == 7) {
        if (listBuilder_ == null) {
          result.value_ = value_;
        } else {
          result.value_ = listBuilder_.build();
        }
      }
      result.valueCase_ = valueCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ctrip.ferriswheel.proto.v1.UnionValue) {
        return mergeFrom((com.ctrip.ferriswheel.proto.v1.UnionValue)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ctrip.ferriswheel.proto.v1.UnionValue other) {
      if (other == com.ctrip.ferriswheel.proto.v1.UnionValue.getDefaultInstance()) return this;
      if (!other.getFormulaString().isEmpty()) {
        formulaString_ = other.formulaString_;
        onChanged();
      }
      switch (other.getValueCase()) {
        case ERROR: {
          setErrorValue(other.getErrorValue());
          break;
        }
        case DECIMAL: {
          valueCase_ = 3;
          value_ = other.value_;
          onChanged();
          break;
        }
        case BOOLEAN: {
          setBoolean(other.getBoolean());
          break;
        }
        case DATE: {
          mergeDate(other.getDate());
          break;
        }
        case STRING: {
          valueCase_ = 6;
          value_ = other.value_;
          onChanged();
          break;
        }
        case LIST: {
          mergeList(other.getList());
          break;
        }
        case VALUE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ctrip.ferriswheel.proto.v1.UnionValue parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ctrip.ferriswheel.proto.v1.UnionValue) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int valueCase_ = 0;
    private java.lang.Object value_;
    public ValueCase
        getValueCase() {
      return ValueCase.forNumber(
          valueCase_);
    }

    public Builder clearValue() {
      valueCase_ = 0;
      value_ = null;
      onChanged();
      return this;
    }


    private java.lang.Object formulaString_ = "";
    /**
     * <code>string formula_string = 1;</code>
     */
    public java.lang.String getFormulaString() {
      java.lang.Object ref = formulaString_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        formulaString_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string formula_string = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFormulaStringBytes() {
      java.lang.Object ref = formulaString_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        formulaString_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string formula_string = 1;</code>
     */
    public Builder setFormulaString(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      formulaString_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string formula_string = 1;</code>
     */
    public Builder clearFormulaString() {
      
      formulaString_ = getDefaultInstance().getFormulaString();
      onChanged();
      return this;
    }
    /**
     * <code>string formula_string = 1;</code>
     */
    public Builder setFormulaStringBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      formulaString_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>.ferriswheel.v1.ErrorCode error = 2;</code>
     */
    public int getErrorValue() {
      if (valueCase_ == 2) {
        return ((java.lang.Integer) value_).intValue();
      }
      return 0;
    }
    /**
     * <code>.ferriswheel.v1.ErrorCode error = 2;</code>
     */
    public Builder setErrorValue(int value) {
      valueCase_ = 2;
      value_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.ferriswheel.v1.ErrorCode error = 2;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.ErrorCode getError() {
      if (valueCase_ == 2) {
        @SuppressWarnings("deprecation")
        com.ctrip.ferriswheel.proto.v1.ErrorCode result = com.ctrip.ferriswheel.proto.v1.ErrorCode.valueOf(
            (java.lang.Integer) value_);
        return result == null ? com.ctrip.ferriswheel.proto.v1.ErrorCode.UNRECOGNIZED : result;
      }
      return com.ctrip.ferriswheel.proto.v1.ErrorCode.EC_UNSET;
    }
    /**
     * <code>.ferriswheel.v1.ErrorCode error = 2;</code>
     */
    public Builder setError(com.ctrip.ferriswheel.proto.v1.ErrorCode value) {
      if (value == null) {
        throw new NullPointerException();
      }
      valueCase_ = 2;
      value_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.ferriswheel.v1.ErrorCode error = 2;</code>
     */
    public Builder clearError() {
      if (valueCase_ == 2) {
        valueCase_ = 0;
        value_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <code>string decimal = 3;</code>
     */
    public java.lang.String getDecimal() {
      java.lang.Object ref = "";
      if (valueCase_ == 3) {
        ref = value_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (valueCase_ == 3) {
          value_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string decimal = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDecimalBytes() {
      java.lang.Object ref = "";
      if (valueCase_ == 3) {
        ref = value_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (valueCase_ == 3) {
          value_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string decimal = 3;</code>
     */
    public Builder setDecimal(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  valueCase_ = 3;
      value_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string decimal = 3;</code>
     */
    public Builder clearDecimal() {
      if (valueCase_ == 3) {
        valueCase_ = 0;
        value_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <code>string decimal = 3;</code>
     */
    public Builder setDecimalBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      valueCase_ = 3;
      value_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>bool boolean = 4;</code>
     */
    public boolean getBoolean() {
      if (valueCase_ == 4) {
        return (java.lang.Boolean) value_;
      }
      return false;
    }
    /**
     * <code>bool boolean = 4;</code>
     */
    public Builder setBoolean(boolean value) {
      valueCase_ = 4;
      value_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool boolean = 4;</code>
     */
    public Builder clearBoolean() {
      if (valueCase_ == 4) {
        valueCase_ = 0;
        value_ = null;
        onChanged();
      }
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> dateBuilder_;
    /**
     * <code>.google.protobuf.Timestamp date = 5;</code>
     */
    public boolean hasDate() {
      return valueCase_ == 5;
    }
    /**
     * <code>.google.protobuf.Timestamp date = 5;</code>
     */
    public com.google.protobuf.Timestamp getDate() {
      if (dateBuilder_ == null) {
        if (valueCase_ == 5) {
          return (com.google.protobuf.Timestamp) value_;
        }
        return com.google.protobuf.Timestamp.getDefaultInstance();
      } else {
        if (valueCase_ == 5) {
          return dateBuilder_.getMessage();
        }
        return com.google.protobuf.Timestamp.getDefaultInstance();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp date = 5;</code>
     */
    public Builder setDate(com.google.protobuf.Timestamp value) {
      if (dateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        value_ = value;
        onChanged();
      } else {
        dateBuilder_.setMessage(value);
      }
      valueCase_ = 5;
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp date = 5;</code>
     */
    public Builder setDate(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (dateBuilder_ == null) {
        value_ = builderForValue.build();
        onChanged();
      } else {
        dateBuilder_.setMessage(builderForValue.build());
      }
      valueCase_ = 5;
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp date = 5;</code>
     */
    public Builder mergeDate(com.google.protobuf.Timestamp value) {
      if (dateBuilder_ == null) {
        if (valueCase_ == 5 &&
            value_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          value_ = com.google.protobuf.Timestamp.newBuilder((com.google.protobuf.Timestamp) value_)
              .mergeFrom(value).buildPartial();
        } else {
          value_ = value;
        }
        onChanged();
      } else {
        if (valueCase_ == 5) {
          dateBuilder_.mergeFrom(value);
        }
        dateBuilder_.setMessage(value);
      }
      valueCase_ = 5;
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp date = 5;</code>
     */
    public Builder clearDate() {
      if (dateBuilder_ == null) {
        if (valueCase_ == 5) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
      } else {
        if (valueCase_ == 5) {
          valueCase_ = 0;
          value_ = null;
        }
        dateBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp date = 5;</code>
     */
    public com.google.protobuf.Timestamp.Builder getDateBuilder() {
      return getDateFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp date = 5;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getDateOrBuilder() {
      if ((valueCase_ == 5) && (dateBuilder_ != null)) {
        return dateBuilder_.getMessageOrBuilder();
      } else {
        if (valueCase_ == 5) {
          return (com.google.protobuf.Timestamp) value_;
        }
        return com.google.protobuf.Timestamp.getDefaultInstance();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp date = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getDateFieldBuilder() {
      if (dateBuilder_ == null) {
        if (!(valueCase_ == 5)) {
          value_ = com.google.protobuf.Timestamp.getDefaultInstance();
        }
        dateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                (com.google.protobuf.Timestamp) value_,
                getParentForChildren(),
                isClean());
        value_ = null;
      }
      valueCase_ = 5;
      onChanged();;
      return dateBuilder_;
    }

    /**
     * <code>string string = 6;</code>
     */
    public java.lang.String getString() {
      java.lang.Object ref = "";
      if (valueCase_ == 6) {
        ref = value_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (valueCase_ == 6) {
          value_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string string = 6;</code>
     */
    public com.google.protobuf.ByteString
        getStringBytes() {
      java.lang.Object ref = "";
      if (valueCase_ == 6) {
        ref = value_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (valueCase_ == 6) {
          value_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string string = 6;</code>
     */
    public Builder setString(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  valueCase_ = 6;
      value_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string string = 6;</code>
     */
    public Builder clearString() {
      if (valueCase_ == 6) {
        valueCase_ = 0;
        value_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <code>string string = 6;</code>
     */
    public Builder setStringBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      valueCase_ = 6;
      value_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.ctrip.ferriswheel.proto.v1.ListValue, com.ctrip.ferriswheel.proto.v1.ListValue.Builder, com.ctrip.ferriswheel.proto.v1.ListValueOrBuilder> listBuilder_;
    /**
     * <code>.ferriswheel.v1.ListValue list = 7;</code>
     */
    public boolean hasList() {
      return valueCase_ == 7;
    }
    /**
     * <code>.ferriswheel.v1.ListValue list = 7;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.ListValue getList() {
      if (listBuilder_ == null) {
        if (valueCase_ == 7) {
          return (com.ctrip.ferriswheel.proto.v1.ListValue) value_;
        }
        return com.ctrip.ferriswheel.proto.v1.ListValue.getDefaultInstance();
      } else {
        if (valueCase_ == 7) {
          return listBuilder_.getMessage();
        }
        return com.ctrip.ferriswheel.proto.v1.ListValue.getDefaultInstance();
      }
    }
    /**
     * <code>.ferriswheel.v1.ListValue list = 7;</code>
     */
    public Builder setList(com.ctrip.ferriswheel.proto.v1.ListValue value) {
      if (listBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        value_ = value;
        onChanged();
      } else {
        listBuilder_.setMessage(value);
      }
      valueCase_ = 7;
      return this;
    }
    /**
     * <code>.ferriswheel.v1.ListValue list = 7;</code>
     */
    public Builder setList(
        com.ctrip.ferriswheel.proto.v1.ListValue.Builder builderForValue) {
      if (listBuilder_ == null) {
        value_ = builderForValue.build();
        onChanged();
      } else {
        listBuilder_.setMessage(builderForValue.build());
      }
      valueCase_ = 7;
      return this;
    }
    /**
     * <code>.ferriswheel.v1.ListValue list = 7;</code>
     */
    public Builder mergeList(com.ctrip.ferriswheel.proto.v1.ListValue value) {
      if (listBuilder_ == null) {
        if (valueCase_ == 7 &&
            value_ != com.ctrip.ferriswheel.proto.v1.ListValue.getDefaultInstance()) {
          value_ = com.ctrip.ferriswheel.proto.v1.ListValue.newBuilder((com.ctrip.ferriswheel.proto.v1.ListValue) value_)
              .mergeFrom(value).buildPartial();
        } else {
          value_ = value;
        }
        onChanged();
      } else {
        if (valueCase_ == 7) {
          listBuilder_.mergeFrom(value);
        }
        listBuilder_.setMessage(value);
      }
      valueCase_ = 7;
      return this;
    }
    /**
     * <code>.ferriswheel.v1.ListValue list = 7;</code>
     */
    public Builder clearList() {
      if (listBuilder_ == null) {
        if (valueCase_ == 7) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
      } else {
        if (valueCase_ == 7) {
          valueCase_ = 0;
          value_ = null;
        }
        listBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ferriswheel.v1.ListValue list = 7;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.ListValue.Builder getListBuilder() {
      return getListFieldBuilder().getBuilder();
    }
    /**
     * <code>.ferriswheel.v1.ListValue list = 7;</code>
     */
    public com.ctrip.ferriswheel.proto.v1.ListValueOrBuilder getListOrBuilder() {
      if ((valueCase_ == 7) && (listBuilder_ != null)) {
        return listBuilder_.getMessageOrBuilder();
      } else {
        if (valueCase_ == 7) {
          return (com.ctrip.ferriswheel.proto.v1.ListValue) value_;
        }
        return com.ctrip.ferriswheel.proto.v1.ListValue.getDefaultInstance();
      }
    }
    /**
     * <code>.ferriswheel.v1.ListValue list = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ctrip.ferriswheel.proto.v1.ListValue, com.ctrip.ferriswheel.proto.v1.ListValue.Builder, com.ctrip.ferriswheel.proto.v1.ListValueOrBuilder> 
        getListFieldBuilder() {
      if (listBuilder_ == null) {
        if (!(valueCase_ == 7)) {
          value_ = com.ctrip.ferriswheel.proto.v1.ListValue.getDefaultInstance();
        }
        listBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ctrip.ferriswheel.proto.v1.ListValue, com.ctrip.ferriswheel.proto.v1.ListValue.Builder, com.ctrip.ferriswheel.proto.v1.ListValueOrBuilder>(
                (com.ctrip.ferriswheel.proto.v1.ListValue) value_,
                getParentForChildren(),
                isClean());
        value_ = null;
      }
      valueCase_ = 7;
      onChanged();;
      return listBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ferriswheel.v1.UnionValue)
  }

  // @@protoc_insertion_point(class_scope:ferriswheel.v1.UnionValue)
  private static final com.ctrip.ferriswheel.proto.v1.UnionValue DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ctrip.ferriswheel.proto.v1.UnionValue();
  }

  public static com.ctrip.ferriswheel.proto.v1.UnionValue getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UnionValue>
      PARSER = new com.google.protobuf.AbstractParser<UnionValue>() {
    @java.lang.Override
    public UnionValue parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UnionValue(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UnionValue> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UnionValue> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ctrip.ferriswheel.proto.v1.UnionValue getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

