// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/ctrip/ferriswheel/proto/workbook.proto

package com.ctrip.ferriswheel.proto.v1;

public final class WorkbookOuterClass {
  private WorkbookOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ferriswheel_v1_Version_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ferriswheel_v1_Version_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ferriswheel_v1_Workbook_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ferriswheel_v1_Workbook_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ferriswheel_v1_Sheet_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ferriswheel_v1_Sheet_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ferriswheel_v1_SheetAsset_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ferriswheel_v1_SheetAsset_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ferriswheel_v1_Table_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ferriswheel_v1_Table_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ferriswheel_v1_Header_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ferriswheel_v1_Header_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ferriswheel_v1_Row_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ferriswheel_v1_Row_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ferriswheel_v1_Cell_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ferriswheel_v1_Cell_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ferriswheel_v1_UnionValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ferriswheel_v1_UnionValue_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ferriswheel_v1_ListValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ferriswheel_v1_ListValue_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ferriswheel_v1_TableAutomaton_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ferriswheel_v1_TableAutomaton_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ferriswheel_v1_QueryAutomaton_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ferriswheel_v1_QueryAutomaton_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ferriswheel_v1_QueryTemplate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ferriswheel_v1_QueryTemplate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ferriswheel_v1_DataQuery_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ferriswheel_v1_DataQuery_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ferriswheel_v1_PivotAutomaton_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ferriswheel_v1_PivotAutomaton_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ferriswheel_v1_PivotFilter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ferriswheel_v1_PivotFilter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ferriswheel_v1_PivotField_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ferriswheel_v1_PivotField_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ferriswheel_v1_PivotValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ferriswheel_v1_PivotValue_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ferriswheel_v1_Parameter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ferriswheel_v1_Parameter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ferriswheel_v1_Chart_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ferriswheel_v1_Chart_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ferriswheel_v1_Series_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ferriswheel_v1_Series_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ferriswheel_v1_Layout_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ferriswheel_v1_Layout_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ferriswheel_v1_Grid_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ferriswheel_v1_Grid_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ferriswheel_v1_Span_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ferriswheel_v1_Span_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ferriswheel_v1_ChartBinder_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ferriswheel_v1_ChartBinder_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ferriswheel_v1_Axis_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ferriswheel_v1_Axis_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ferriswheel_v1_Interval_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ferriswheel_v1_Interval_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ferriswheel_v1_AxisBand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ferriswheel_v1_AxisBand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ferriswheel_v1_Color_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ferriswheel_v1_Color_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ferriswheel_v1_Text_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ferriswheel_v1_Text_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ferriswheel_v1_Form_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ferriswheel_v1_Form_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ferriswheel_v1_FormField_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ferriswheel_v1_FormField_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ferriswheel_v1_FormFieldBinding_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ferriswheel_v1_FormFieldBinding_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*com/ctrip/ferriswheel/proto/workbook.p" +
      "roto\022\016ferriswheel.v1\032\037google/protobuf/ti" +
      "mestamp.proto\"6\n\007Version\022\r\n\005major\030\001 \001(\r\022" +
      "\r\n\005minor\030\002 \001(\r\022\r\n\005build\030\003 \001(\r\"x\n\010Workboo" +
      "k\022(\n\007version\030\001 \001(\0132\027.ferriswheel.v1.Vers" +
      "ion\022\r\n\005flags\030\002 \001(\004\022\014\n\004name\030\003 \001(\t\022%\n\006shee" +
      "ts\030\004 \003(\0132\025.ferriswheel.v1.Sheet\"i\n\005Sheet" +
      "\022\014\n\004name\030\001 \001(\t\022*\n\006assets\030\002 \003(\0132\032.ferrisw" +
      "heel.v1.SheetAsset\022&\n\006layout\030\003 \001(\0132\026.fer" +
      "riswheel.v1.Layout\"\261\001\n\nSheetAsset\022&\n\005tab" +
      "le\030\001 \001(\0132\025.ferriswheel.v1.TableH\000\022&\n\005cha" +
      "rt\030\002 \001(\0132\025.ferriswheel.v1.ChartH\000\022$\n\004tex" +
      "t\030\003 \001(\0132\024.ferriswheel.v1.TextH\000\022$\n\004form\030" +
      "\004 \001(\0132\024.ferriswheel.v1.FormH\000B\007\n\005asset\"\360" +
      "\001\n\005Table\022\014\n\004name\030\001 \001(\t\022!\n\004rows\030\002 \003(\0132\023.f" +
      "erriswheel.v1.Row\0221\n\tautomaton\030\003 \001(\0132\036.f" +
      "erriswheel.v1.TableAutomaton\022&\n\006layout\030\004" +
      " \001(\0132\026.ferriswheel.v1.Layout\022+\n\013row_head" +
      "ers\030\005 \003(\0132\026.ferriswheel.v1.Header\022.\n\016col" +
      "umn_headers\030\006 \003(\0132\026.ferriswheel.v1.Heade" +
      "r\"\010\n\006Header\"=\n\003Row\022\021\n\trow_index\030\001 \001(\005\022#\n" +
      "\005cells\030\002 \003(\0132\024.ferriswheel.v1.Cell\"W\n\004Ce" +
      "ll\022\024\n\014column_index\030\001 \001(\005\022)\n\005value\030\002 \001(\0132" +
      "\032.ferriswheel.v1.UnionValue\022\016\n\006format\030\003 " +
      "\001(\t\"\350\001\n\nUnionValue\022\026\n\016formula_string\030\001 \001" +
      "(\t\022*\n\005error\030\002 \001(\0162\031.ferriswheel.v1.Error" +
      "CodeH\000\022\021\n\007decimal\030\003 \001(\tH\000\022\021\n\007boolean\030\004 \001" +
      "(\010H\000\022*\n\004date\030\005 \001(\0132\032.google.protobuf.Tim" +
      "estampH\000\022\020\n\006string\030\006 \001(\tH\000\022)\n\004list\030\007 \001(\013" +
      "2\031.ferriswheel.v1.ListValueH\000B\007\n\005value\"G" +
      "\n\tListValue\022)\n\005items\030\001 \003(\0132\032.ferriswheel" +
      ".v1.UnionValue\022\017\n\007columns\030\002 \001(\005\"\223\001\n\016Tabl" +
      "eAutomaton\0229\n\017query_automaton\030\001 \001(\0132\036.fe" +
      "rriswheel.v1.QueryAutomatonH\000\0229\n\017pivot_a" +
      "utomaton\030\002 \001(\0132\036.ferriswheel.v1.PivotAut" +
      "omatonH\000B\013\n\tautomaton\"\226\001\n\016QueryAutomaton" +
      "\022/\n\010template\030\001 \001(\0132\035.ferriswheel.v1.Quer" +
      "yTemplate\022)\n\006params\030\002 \003(\0132\031.ferriswheel." +
      "v1.Parameter\022(\n\005query\030\003 \001(\0132\031.ferriswhee" +
      "l.v1.DataQuery\"R\n\rQueryTemplate\022\016\n\006schem" +
      "e\030\001 \001(\t\0221\n\016builtin_params\030\002 \003(\0132\031.ferris" +
      "wheel.v1.Parameter\"F\n\tDataQuery\022\016\n\006schem" +
      "e\030\001 \001(\t\022)\n\006params\030\002 \003(\0132\031.ferriswheel.v1" +
      ".Parameter\"\353\001\n\016PivotAutomaton\022(\n\004data\030\001 " +
      "\001(\0132\032.ferriswheel.v1.UnionValue\022,\n\007filte" +
      "rs\030\002 \003(\0132\033.ferriswheel.v1.PivotFilter\022(\n" +
      "\004rows\030\003 \003(\0132\032.ferriswheel.v1.PivotField\022" +
      "+\n\007columns\030\004 \003(\0132\032.ferriswheel.v1.PivotF" +
      "ield\022*\n\006values\030\005 \003(\0132\032.ferriswheel.v1.Pi" +
      "votValue\"\034\n\013PivotFilter\022\r\n\005field\030\001 \001(\t\"+" +
      "\n\nPivotField\022\r\n\005field\030\001 \001(\t\022\016\n\006format\030\002 " +
      "\001(\t\"q\n\nPivotValue\022\r\n\005field\030\001 \001(\t\0225\n\016aggr" +
      "egate_type\030\002 \001(\0162\035.ferriswheel.v1.Aggreg" +
      "ateType\022\r\n\005label\030\003 \001(\t\022\016\n\006format\030\004 \001(\t\"\224" +
      "\001\n\tParameter\022\014\n\004name\030\001 \001(\t\022)\n\005value\030\002 \001(" +
      "\0132\032.ferriswheel.v1.UnionValue\022)\n\004type\030\003 " +
      "\001(\0162\033.ferriswheel.v1.VariantType\022\021\n\tmand" +
      "atory\030\004 \001(\010\022\020\n\010multiple\030\005 \001(\010\"\355\002\n\005Chart\022" +
      "\014\n\004name\030\001 \001(\t\022\014\n\004type\030\002 \001(\t\022)\n\005title\030\003 \001" +
      "(\0132\032.ferriswheel.v1.UnionValue\022.\n\ncatego" +
      "ries\030\004 \001(\0132\032.ferriswheel.v1.UnionValue\022&" +
      "\n\006series\030\005 \003(\0132\026.ferriswheel.v1.Series\022&" +
      "\n\006layout\030\006 \001(\0132\026.ferriswheel.v1.Layout\022+" +
      "\n\006binder\030\007 \001(\0132\033.ferriswheel.v1.ChartBin" +
      "der\022$\n\006x_axis\030\010 \001(\0132\024.ferriswheel.v1.Axi" +
      "s\022$\n\006y_axis\030\t \001(\0132\024.ferriswheel.v1.Axis\022" +
      "$\n\006z_axis\030\n \001(\0132\024.ferriswheel.v1.Axis\"\274\001" +
      "\n\006Series\022(\n\004name\030\001 \001(\0132\032.ferriswheel.v1." +
      "UnionValue\022,\n\010x_values\030\002 \001(\0132\032.ferriswhe" +
      "el.v1.UnionValue\022,\n\010y_values\030\003 \001(\0132\032.fer" +
      "riswheel.v1.UnionValue\022,\n\010z_values\030\004 \001(\013" +
      "2\032.ferriswheel.v1.UnionValue\"\322\001\n\006Layout\022" +
      "(\n\007display\030\001 \001(\0162\027.ferriswheel.v1.Displa" +
      "y\022\r\n\005width\030\002 \001(\005\022\016\n\006height\030\003 \001(\005\022(\n\005alig" +
      "n\030\004 \001(\0162\031.ferriswheel.v1.Placement\0221\n\016ve" +
      "rtical_align\030\005 \001(\0162\031.ferriswheel.v1.Plac" +
      "ement\022\"\n\004grid\030\006 \001(\0132\024.ferriswheel.v1.Gri" +
      "d\"n\n\004Grid\022\017\n\007columns\030\001 \001(\005\022\014\n\004rows\030\002 \001(\005" +
      "\022$\n\006column\030\003 \001(\0132\024.ferriswheel.v1.Span\022!" +
      "\n\003row\030\004 \001(\0132\024.ferriswheel.v1.Span\"\"\n\004Spa" +
      "n\022\r\n\005start\030\001 \001(\005\022\013\n\003end\030\002 \001(\005\"\334\001\n\013ChartB" +
      "inder\022(\n\004data\030\001 \001(\0132\032.ferriswheel.v1.Uni" +
      "onValue\0220\n\013orientation\030\002 \001(\0162\033.ferriswhe" +
      "el.v1.Orientation\0227\n\024categories_placemen" +
      "t\030\003 \001(\0162\031.ferriswheel.v1.Placement\0228\n\025se" +
      "ries_name_placement\030\004 \001(\0162\031.ferriswheel." +
      "v1.Placement\"\365\001\n\004Axis\022\r\n\005title\030\001 \001(\t\022\r\n\005" +
      "label\030\002 \001(\t\022,\n\tplacement\030\003 \001(\0162\031.ferrisw" +
      "heel.v1.Placement\022\020\n\010reversed\030\004 \001(\010\022*\n\010i" +
      "nterval\030\005 \001(\0132\030.ferriswheel.v1.Interval\022" +
      "\'\n\005bands\030\006 \003(\0132\030.ferriswheel.v1.AxisBand" +
      "\022*\n\010stacking\030\007 \001(\0162\030.ferriswheel.v1.Stac" +
      "king\022\016\n\006format\030\010 \001(\t\"$\n\010Interval\022\014\n\004from" +
      "\030\001 \001(\001\022\n\n\002to\030\002 \001(\001\"k\n\010AxisBand\022*\n\010interv" +
      "al\030\001 \001(\0132\030.ferriswheel.v1.Interval\022\r\n\005la" +
      "bel\030\002 \001(\t\022$\n\005color\030\003 \001(\0132\025.ferriswheel.v" +
      "1.Color\"@\n\005Color\022\013\n\003red\030\001 \001(\002\022\r\n\005green\030\002" +
      " \001(\002\022\014\n\004blue\030\003 \001(\002\022\r\n\005alpha\030\004 \001(\002\"i\n\004Tex" +
      "t\022\014\n\004name\030\001 \001(\t\022+\n\007content\030\002 \001(\0132\032.ferri" +
      "swheel.v1.UnionValue\022&\n\006layout\030\003 \001(\0132\026.f" +
      "erriswheel.v1.Layout\"g\n\004Form\022\014\n\004name\030\001 \001" +
      "(\t\022)\n\006fields\030\002 \003(\0132\031.ferriswheel.v1.Form" +
      "Field\022&\n\006layout\030\003 \001(\0132\026.ferriswheel.v1.L" +
      "ayout\"\222\002\n\tFormField\022\014\n\004name\030\001 \001(\t\022)\n\004typ" +
      "e\030\002 \001(\0162\033.ferriswheel.v1.VariantType\022)\n\005" +
      "value\030\003 \001(\0132\032.ferriswheel.v1.UnionValue\022" +
      "\021\n\tmandatory\030\004 \001(\010\022\020\n\010multiple\030\005 \001(\010\022\r\n\005" +
      "label\030\006 \001(\t\022\014\n\004tips\030\007 \001(\t\022+\n\007options\030\010 \001" +
      "(\0132\032.ferriswheel.v1.UnionValue\0222\n\010bindin" +
      "gs\030\t \003(\0132 .ferriswheel.v1.FormFieldBindi" +
      "ng\"\"\n\020FormFieldBinding\022\016\n\006target\030\001 \001(\t*\205" +
      "\001\n\tErrorCode\022\014\n\010EC_UNSET\020\000\022\013\n\007EC_NULL\020\001\022" +
      "\n\n\006EC_DIV\020\002\022\014\n\010EC_VALUE\020\003\022\n\n\006EC_REF\020\004\022\013\n" +
      "\007EC_NAME\020\005\022\n\n\006EC_NUM\020\006\022\t\n\005EC_NA\020\007\022\023\n\017EC_" +
      "GETTING_DATA\020\010*\223\002\n\rAggregateType\022\014\n\010AT_U" +
      "NSET\020\000\022\016\n\nAT_SUMMARY\020\001\022\014\n\010AT_COUNT\020\002\022\016\n\n" +
      "AT_AVERAGE\020\003\022\016\n\nAT_MAXIMUM\020\004\022\016\n\nAT_MINIM" +
      "UM\020\005\022\016\n\nAT_PRODUCT\020\006\022\031\n\025AT_DECIMAL_ONLY_" +
      "COUNT\020\007\022\031\n\025AT_STANDARD_DEVIATION\020\010\022$\n AT" +
      "_STANDARD_DEVIATION_POPULATION\020\t\022\017\n\013AT_V" +
      "ARIANCE\020\n\022\032\n\026AT_VARIANCE_POPULATION\020\013\022\r\n" +
      "\tAT_CUSTOM\020\014*}\n\013VariantType\022\014\n\010VT_UNSET\020" +
      "\000\022\014\n\010VT_ERROR\020\001\022\014\n\010VT_BLANK\020\002\022\016\n\nVT_DECI" +
      "MAL\020\003\022\013\n\007VT_BOOL\020\004\022\013\n\007VT_DATE\020\005\022\r\n\tVT_ST" +
      "RING\020\006\022\013\n\007VT_LIST\020\007*G\n\007Display\022\016\n\nDISP_U" +
      "NSET\020\000\022\r\n\tDISP_NONE\020\001\022\016\n\nDISP_BLOCK\020\002\022\r\n" +
      "\tDISP_GRID\020\005*K\n\013Orientation\022\020\n\014ORIENT_UN" +
      "SET\020\000\022\025\n\021ORIENT_HORIZONTAL\020\001\022\023\n\017ORIENT_V" +
      "ERTICAL\020\002*p\n\tPlacement\022\017\n\013PLCMT_UNSET\020\000\022" +
      "\016\n\nPLCMT_LEFT\020\001\022\r\n\tPLCMT_TOP\020\002\022\017\n\013PLCMT_" +
      "RIGHT\020\003\022\020\n\014PLCMT_BOTTOM\020\004\022\020\n\014PLCMT_CENTE" +
      "R\020\005*K\n\010Stacking\022\022\n\016STACKING_UNSET\020\000\022\025\n\021S" +
      "TACKING_ABSOLUTE\020\001\022\024\n\020STACKING_PERCENT\020\002" +
      "B\"\n\036com.ctrip.ferriswheel.proto.v1P\001b\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_ferriswheel_v1_Version_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ferriswheel_v1_Version_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ferriswheel_v1_Version_descriptor,
        new java.lang.String[] { "Major", "Minor", "Build", });
    internal_static_ferriswheel_v1_Workbook_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ferriswheel_v1_Workbook_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ferriswheel_v1_Workbook_descriptor,
        new java.lang.String[] { "Version", "Flags", "Name", "Sheets", });
    internal_static_ferriswheel_v1_Sheet_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ferriswheel_v1_Sheet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ferriswheel_v1_Sheet_descriptor,
        new java.lang.String[] { "Name", "Assets", "Layout", });
    internal_static_ferriswheel_v1_SheetAsset_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ferriswheel_v1_SheetAsset_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ferriswheel_v1_SheetAsset_descriptor,
        new java.lang.String[] { "Table", "Chart", "Text", "Form", "Asset", });
    internal_static_ferriswheel_v1_Table_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_ferriswheel_v1_Table_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ferriswheel_v1_Table_descriptor,
        new java.lang.String[] { "Name", "Rows", "Automaton", "Layout", "RowHeaders", "ColumnHeaders", });
    internal_static_ferriswheel_v1_Header_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_ferriswheel_v1_Header_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ferriswheel_v1_Header_descriptor,
        new java.lang.String[] { });
    internal_static_ferriswheel_v1_Row_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_ferriswheel_v1_Row_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ferriswheel_v1_Row_descriptor,
        new java.lang.String[] { "RowIndex", "Cells", });
    internal_static_ferriswheel_v1_Cell_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_ferriswheel_v1_Cell_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ferriswheel_v1_Cell_descriptor,
        new java.lang.String[] { "ColumnIndex", "Value", "Format", });
    internal_static_ferriswheel_v1_UnionValue_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_ferriswheel_v1_UnionValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ferriswheel_v1_UnionValue_descriptor,
        new java.lang.String[] { "FormulaString", "Error", "Decimal", "Boolean", "Date", "String", "List", "Value", });
    internal_static_ferriswheel_v1_ListValue_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_ferriswheel_v1_ListValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ferriswheel_v1_ListValue_descriptor,
        new java.lang.String[] { "Items", "Columns", });
    internal_static_ferriswheel_v1_TableAutomaton_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_ferriswheel_v1_TableAutomaton_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ferriswheel_v1_TableAutomaton_descriptor,
        new java.lang.String[] { "QueryAutomaton", "PivotAutomaton", "Automaton", });
    internal_static_ferriswheel_v1_QueryAutomaton_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_ferriswheel_v1_QueryAutomaton_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ferriswheel_v1_QueryAutomaton_descriptor,
        new java.lang.String[] { "Template", "Params", "Query", });
    internal_static_ferriswheel_v1_QueryTemplate_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_ferriswheel_v1_QueryTemplate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ferriswheel_v1_QueryTemplate_descriptor,
        new java.lang.String[] { "Scheme", "BuiltinParams", });
    internal_static_ferriswheel_v1_DataQuery_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_ferriswheel_v1_DataQuery_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ferriswheel_v1_DataQuery_descriptor,
        new java.lang.String[] { "Scheme", "Params", });
    internal_static_ferriswheel_v1_PivotAutomaton_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_ferriswheel_v1_PivotAutomaton_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ferriswheel_v1_PivotAutomaton_descriptor,
        new java.lang.String[] { "Data", "Filters", "Rows", "Columns", "Values", });
    internal_static_ferriswheel_v1_PivotFilter_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_ferriswheel_v1_PivotFilter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ferriswheel_v1_PivotFilter_descriptor,
        new java.lang.String[] { "Field", });
    internal_static_ferriswheel_v1_PivotField_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_ferriswheel_v1_PivotField_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ferriswheel_v1_PivotField_descriptor,
        new java.lang.String[] { "Field", "Format", });
    internal_static_ferriswheel_v1_PivotValue_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_ferriswheel_v1_PivotValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ferriswheel_v1_PivotValue_descriptor,
        new java.lang.String[] { "Field", "AggregateType", "Label", "Format", });
    internal_static_ferriswheel_v1_Parameter_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_ferriswheel_v1_Parameter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ferriswheel_v1_Parameter_descriptor,
        new java.lang.String[] { "Name", "Value", "Type", "Mandatory", "Multiple", });
    internal_static_ferriswheel_v1_Chart_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_ferriswheel_v1_Chart_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ferriswheel_v1_Chart_descriptor,
        new java.lang.String[] { "Name", "Type", "Title", "Categories", "Series", "Layout", "Binder", "XAxis", "YAxis", "ZAxis", });
    internal_static_ferriswheel_v1_Series_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_ferriswheel_v1_Series_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ferriswheel_v1_Series_descriptor,
        new java.lang.String[] { "Name", "XValues", "YValues", "ZValues", });
    internal_static_ferriswheel_v1_Layout_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_ferriswheel_v1_Layout_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ferriswheel_v1_Layout_descriptor,
        new java.lang.String[] { "Display", "Width", "Height", "Align", "VerticalAlign", "Grid", });
    internal_static_ferriswheel_v1_Grid_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_ferriswheel_v1_Grid_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ferriswheel_v1_Grid_descriptor,
        new java.lang.String[] { "Columns", "Rows", "Column", "Row", });
    internal_static_ferriswheel_v1_Span_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_ferriswheel_v1_Span_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ferriswheel_v1_Span_descriptor,
        new java.lang.String[] { "Start", "End", });
    internal_static_ferriswheel_v1_ChartBinder_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_ferriswheel_v1_ChartBinder_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ferriswheel_v1_ChartBinder_descriptor,
        new java.lang.String[] { "Data", "Orientation", "CategoriesPlacement", "SeriesNamePlacement", });
    internal_static_ferriswheel_v1_Axis_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_ferriswheel_v1_Axis_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ferriswheel_v1_Axis_descriptor,
        new java.lang.String[] { "Title", "Label", "Placement", "Reversed", "Interval", "Bands", "Stacking", "Format", });
    internal_static_ferriswheel_v1_Interval_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_ferriswheel_v1_Interval_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ferriswheel_v1_Interval_descriptor,
        new java.lang.String[] { "From", "To", });
    internal_static_ferriswheel_v1_AxisBand_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_ferriswheel_v1_AxisBand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ferriswheel_v1_AxisBand_descriptor,
        new java.lang.String[] { "Interval", "Label", "Color", });
    internal_static_ferriswheel_v1_Color_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_ferriswheel_v1_Color_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ferriswheel_v1_Color_descriptor,
        new java.lang.String[] { "Red", "Green", "Blue", "Alpha", });
    internal_static_ferriswheel_v1_Text_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_ferriswheel_v1_Text_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ferriswheel_v1_Text_descriptor,
        new java.lang.String[] { "Name", "Content", "Layout", });
    internal_static_ferriswheel_v1_Form_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_ferriswheel_v1_Form_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ferriswheel_v1_Form_descriptor,
        new java.lang.String[] { "Name", "Fields", "Layout", });
    internal_static_ferriswheel_v1_FormField_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_ferriswheel_v1_FormField_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ferriswheel_v1_FormField_descriptor,
        new java.lang.String[] { "Name", "Type", "Value", "Mandatory", "Multiple", "Label", "Tips", "Options", "Bindings", });
    internal_static_ferriswheel_v1_FormFieldBinding_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_ferriswheel_v1_FormFieldBinding_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ferriswheel_v1_FormFieldBinding_descriptor,
        new java.lang.String[] { "Target", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
